### ISSUE TITLE
convert image data to js object

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#135]
https://github.com/ChickenKyiv/awesome-food-measurements-information/blob/master/images/cooking-guide-apron-cu-cooking-times.jpg

@elnur004 you can grab it

**Comment by atherdon** [comment]
if you'll do it quickly and i will reply slow, you can also grab this image as well(each data should have separated file): https://github.com/ChickenKyiv/awesome-food-measurements-information/blob/master/images/c7cddf12c4969f80c77cd23d6d38243c.jpg

**Comment by atherdon** [comment]
Next stage will be to add tests for each new file

**Comment by elnur004** [comment]
may you say how to do this, please?

**Comment by atherdon** [comment]
just similar to your previous task:
* add a new file at folder `__tests__`
* copy paste data from another test file
* change import of data into that file
* change the text of test

**Comment by elnur004** [comment]
i want to know how to change import of data? 
how to trace files?
is there any folder or JSON file?
or just to trace `import`....`from` GroceriStar/sd/and file name?

**Comment by elnur004** [comment]
hi,
@atherdon what we need to do now? 
is there any task for me?

**Comment by vadim9999** [comment]
@atherdon I suppose you need to generate files. See how to generate it in https://github.com/GroceriStar/sd/issues/55#issuecomment-484837676

**Comment by atherdon** [comment]
@vadim I don't want to generate them :( please explain it to Elnur and
follow him at this task

>

**Comment by vadim9999** [comment]
@elnur004 
>i want to know how to change import of data?
> how to trace files?
> is there any folder or JSON file?
> or just to trace import....from GroceriStar/sd/and file name?


Have you copy paste data from another test files? If yes, then
for example allergy.test.js has import 
```
import allergies from '~/Allergy/allergies.json'
```
`~`  this symbol cut path(instead of this symbol babel add ./src/data), full path to file without this symbol will be

```
import allergies from './src/data/Allergy/allergies.json'
```

 change this '~/Allergy/allergies.json' on your path that you have saved your file 
then change variable of import in example it allergies.

**Comment by elnur004** [comment]
@vadim9999 for instance: i've done files like this way `import dash from '~/GroceriStar/cd/dash.js'` already. 
and so on other files... (they exist in _test_ folder)
if that way is correct let me know please, what to do then on?

**Comment by vadim9999** [comment]
@atherdon it's task is done for elnur?

**Comment by vadim9999** [comment]
> if you'll do it quickly and i will reply slow, you can also grab this image as well(each data should have separated file): https://github.com/ChickenKyiv/awesome-food-measurements-information/blob/master/images/c7cddf12c4969f80c77cd23d6d38243c.jpg

@elnur004 have done this ?

**Comment by elnur004** [comment]
hi, @vadim9999 
no problem.
yes, i've done this and they exist in **task** folder

**Comment by atherdon** [comment]
#174 @elnur004 please show it to @vadim9999 he will supervise you, while i'm busy

**Comment by vadim9999** [comment]
@elnur004 
Can you give me a link where you converted data from image into object I can find it

**Comment by vadim9999** [comment]
@atherdon tests doesn't work when using es6 import, working when using es5 require

**Comment by elnur004** [comment]
@vadim9999 
https://github.com/GroceriStar/sd/tree/master/src/data/__tests__
these are tests files

**Comment by elnur004** [comment]
> @elnur004
> Can you give me a link of file where you converted data from image into object I can find it

https://github.com/ChickenKyiv/awesome-food-measurements-information

**Comment by elnur004** [comment]
@vadim9999 
need we change these to es5?

**Comment by vadim9999** [comment]
> @vadim9999
> need we change these to es5?

No, I have fix this place update your local repository

**Comment by elnur004** [comment]
> > @vadim9999 
> No, I have fix this please update your local repository

sorry for question.
but how to update local repository?

**Comment by vadim9999** [comment]
@elnur004 All of objects that you have added in root directory cooking-times.js, cup1-2.js .. etc. Now doesn't work because it's haven't exported. and tests because it's import is incorrect. 
I For example I will take dash.js and dash.test.js
To fix this you need 
1. export object dash. to do this you need in dash.js in the end of file add
```
export default dash;
```
2. import this object in dash.test.js. 
Now dash.test.js has this frong path 
```
import dash from '~/GroceriStar/cd/dash.js'
```
It's doesn't work because this path doesn't exist.
You need make this 
```
import dash from '../../../dash'
```
../ this means that like "exit" from current folder
for example you have this directory
main
|_ subfolder
     |_files.js
|_manyfiles.js
to open file manyfiles.js in folder main you will need use '../manyfyles' in files.js that is subfolder of main
Make this changes for other files that you have added

**Comment by vadim9999** [comment]
> > > @vadim9999
> > > No, I have fix this please update your local repository
> 
> sorry for question.
> but how to update local repository?

you just need in your project use
```
git pull https://github.com/GroceriStar/sd.git
```

**Comment by elnur004** [comment]
@vadim9999 

i stuck in cooking-times.js/cooking-times here.
how i have to trace here?
must i export cooking-times from in cooking-times.js file?
for example:
`import cooking-times from '../cd/cooking-times.js'`
is this a correct tracking?

**Comment by elnur004** [comment]
i want to understand from where we import the test

**Comment by vadim9999** [comment]
@elnur004 
we have tests in sd/src/data/__tests__
sd is a folder project
object cooking-times.js is in sd, also other objects is in this folder
in cooking-times.js you have exported object that we can get acces to it from other files

**Comment by elnur004** [comment]
then, 
i have to trace 
import cooking-times from '../src/data/tests/cooking-times.js'
right?

**Comment by vadim9999** [comment]
@elnur004 but why you need to import tests? you need in file tests import object

**Comment by vadim9999** [comment]
@elnur004 
if you will write in dash.test.js 
import dash from '../../../dash'

this will work another variant doesn't work. in cooking-times.js import like below and change instead of dash cooking-times.js
in result you import will be 
```
import dash from '../../../cooking-times'
```

**Comment by elnur004** [comment]
i want to fill up that dots))
before the /cooking-times i don't know to show cooking-times.js or not

**Comment by elnur004** [comment]
i have stuck in there

**Comment by vadim9999** [comment]
just insert import 
```
import cooking-times from '../../../cooking-times'

```
it will work

**Comment by elnur004** [comment]
`import cooking-times from '../src/data/tests/cooking-times'`

like this?

**Comment by vadim9999** [comment]
no
in cooking-times.test.js
insert 
```
import cooking-times from '../../../cooking-times'
```

**Comment by vadim9999** [comment]
don't fiil up dots

**Comment by elnur004** [comment]
@vadim9999 
may you explain please, why those dots wouldn't be filled up?
it has been obscure for me

**Comment by vadim9999** [comment]
ok,
for example now you are in folder tests you need to get access to file that located in folder up to get access you should use ../ . if need to get access upper folder in result it will be ../../

**Comment by vadim9999** [comment]
./ it get access to files that located in current folder but if you want to get file that located out of current folder using ../

**Comment by vadim9999** [comment]
now you are in sd/src/data/tests  using ./ you can get files related in folder tests. to get files related in `data` folder use ../ and if you  want use files that located in folder srs use ../../ then if you want to get files from project folder ../../../

**Comment by elnur004** [comment]
thanx, a lot @vadim9999 ,
it was very helpful for me

**Comment by vadim9999** [comment]
@elnur004 Sorry I thouhgt in file cooking-times.js is one object. change export default cooking-time on this structure
```
export {
frenchBeans,
sprouts,
//..and so on add all object in this curl brackets that are in this files  
}
```
and change import in cooking-times.js 
instead of
``` 
import { frenchBeans, sprouts}  from '../../../cooking-times'
```

**Comment by elnur004** [comment]
ok

**Comment by elnur004** [comment]
need there to write `default` after `export`?

**Comment by vadim9999** [comment]
no

**Comment by elnur004** [comment]
why?
what is the difference between previous and this?

**Comment by vadim9999** [comment]
export default when you export one object and export { .. } some objects

**Comment by elnur004** [comment]
i've caught it up
but i want to grasp what is the meaning of default in here?

**Comment by elnur004** [comment]
sorry i'm giving you trouble

**Comment by vadim9999** [comment]
more information you can read in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

**Comment by vadim9999** [comment]
add moore tests in block describe https://github.com/GroceriStar/sd/blob/master/src/data/__tests__/cooking_times.test.js

**Comment by vadim9999** [comment]
For example 
describe('this test prevents to any issues and problems, also to break the structure of cooking_times data', () => {
  test('cooking_times data files returns object', () => {
    expect(cooking_times).not.toBe('')
  }),
 test('cooking_times data files returns object', () => {
    expect(cooking_times).not.toBe('')
  }),
 test('cooking_times data files returns object', () => {
    expect(cooking_times).not.toBe('')
  })
})

**Comment by vadim9999** [comment]
@elnur004 please can you create one pull request and many commits?

**Comment by elnur004** [comment]
i don't know how to do this

**Comment by vadim9999** [comment]
also you can run tests by
```
npm run tests
```

**Comment by elnur004** [comment]
@vadim9999 i am a novice in this sphere
i don't know a lot of things but i'm trying to learn

**Comment by vadim9999** [comment]
you have forked repository, right? you make some changes 
then git add * 
git commit -m "comment"
git push 
after that if you have created pull request it will automaticall add's commit to pull request(PR) if you haven't any PR you can create it

**Comment by elnur004** [comment]
i have forked a long time ago but i can't see a lot of changes in there now
i dont know why

**Comment by vadim9999** [comment]
and what are you doing?

**Comment by elnur004** [comment]
wait. i'm gravelled...

**Comment by elnur004** [comment]
))

**Comment by elnur004** [comment]
i will try to do

**Comment by elnur004** [comment]
@vadim9999 
what needs to do now?

**Comment by vadim9999** [comment]
@elnur004 gave you Artur some task?

**Comment by elnur004** [comment]
the last task was this

**Comment by vadim9999** [comment]
@elnur004 I can give you task, but I don't know can you do this or not. It's need to fix some failed tests. 
to run tests you need 
```
npm run test
```

**Comment by elnur004** [comment]
to solve this task, need me to know node.js?

**Comment by vadim9999** [comment]
@elnur004 yes. Do you have this?

**Comment by elnur004** [comment]
i want to do. and besides this, i think it will profitable for me to learn node.js
btw may i ask you some question if there will be any problem to solve this task to me?

**Comment by vadim9999** [comment]
@elnur004 import and export objects from files that you had working in https://github.com/GroceriStar/sd/blob/master/src/files.js .

**Comment by vadim9999** [comment]
@elnur004 I think if you will make last comment I will close this issues

**Comment by elnur004** [comment]
i don't know, need me to download anything to computer to run this?

**Comment by vadim9999** [comment]
@elnur004 do you mean to run tests?

**Comment by elnur004** [comment]
yes

**Comment by vadim9999** [comment]
to run tests you should install nodejs then 
in the root project 
```
npm install
```
 (this command will download all packages that was defined in package.json)
then you can run npm run test

**Comment by vadim9999** [comment]
also to know that tests is working you can in pull request besides your commit click details and see result of tests

**Comment by vadim9999** [comment]
@have you imported exported objects in files.js that you had working?

**Comment by elnur004** [comment]
need me to change JSON files and export these?

**Comment by vadim9999** [comment]
@elnur004 no, first you need to import object then export it in files.js. It need because to get your object from outside of package

**Comment by elnur004** [comment]
@vadim9999 these JSON files confuse me
may you give me some hint, please?

**Comment by vadim9999** [comment]
@elnur004 in path when you want import object from .json you should use .json. when you import object from js you don't need to use filename with extension, just filename. In you case you should use just filename in path because you files have extension .js

**Comment by elnur004** [comment]
@vadim9999 sorry for the question but from which file i have to export file and to which file i have to import?
