### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#176]
Add explanation in Readme 
- [x] related to module resolver in files.js(that is in root). Write why need variable __dirname, what we get when call path.resolver.
- [x] describe why we using alias ~ . what path babel insert instead of this symbol.(definision of alias you can see in babel.config.js in constant plugins)
- [x] describe methods that you have added in generateArray.js in section generateArray of Readme. How to import it, call this function and what is return (you can add small output of object).

**Comment by hirdbluebird** [comment]
https://github.com/GroceriStar/sd/pull/295

**Comment by hirdbluebird** [comment]
@atherdon check the pull request 
https://github.com/GroceriStar/sd/pull/295

**Comment by atherdon** [comment]
yeah i saw it. as i'm not team lead at this repo - I cannot merge it. i add you just to avoid confusion

**Comment by atherdon** [comment]
@vadim9999 please close it if it completed

**Comment by vadim9999** [comment]
close
