### ISSUE TITLE
fix tests that failures and fix imports in files.js

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#204]
to check tests you can 
```
npm run tests
```
or open in pull request besides commit clicking details

**Comment by wahaj-47** [comment]
#207 Fixed one failing test.
The other two are due to missing JSONs. Are we going to generate those JSONs ?

**Comment by vadim9999** [comment]
Now we can on pause this two files. I will find out why we need it files.

**Comment by vadim9999** [comment]
@wahaj-47 please change in src/files.js in import generatedMeasurementSystems on generatedMeasurementSystem (without s) also in path.

**Comment by vadim9999** [comment]
@wahaj-47 you can start this task https://github.com/GroceriStar/sd/issues/208

**Comment by wahaj-47** [comment]
Close this issue as well

**Comment by vadim9999** [comment]
close
