### ISSUE TITLE
replace paths with module resolver paths in tests

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#208]
In root of project is files.js. You need import from this file certain variable.
For example in allergy.test.js replace import on 
```
import { allergiesFilePath } from '../../../files'
```
make it to all tests

**Comment by wahaj-47** [comment]
I don't understand. Do you want me use path.resolve ??

**Comment by vadim9999** [comment]
no, I mean import variables from files.js that is located in project folder

**Comment by vadim9999** [comment]
@wahaj-47 please change variables that was before (allergiestFilePath) in files.js and tests

**Comment by vadim9999** [comment]
@wahaj-47 after it tests will not working but we can fix it. 
After you will change all variables we will have this 
```
import { allergiesFilePath } from '../../../files';
```
then allergiesFilePath contain full path from your disk. First issue I have founded it's add use require.
I think we can change import on require.
Please change import in tests like this 
```
const { allergiesFilePath } = require('../../../files')
const allergies = require(allergiesFilePath)
```

**Comment by wahaj-47** [comment]
How about we do this ?
`import {allergiesFilePath as allergies} from '../../../files.js'`

**Comment by vadim9999** [comment]
@wahaj-47 No, it's just get full path of file. The issue is that we can't set in import path variable in es6 but in es5 we can do it with require it like a method that you can use everywhere
