### ISSUE TITLE
export files that was added in src/files.js

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#209]
Import then export variable

**Comment by vadim9999** [comment]
@elnur004 please ask questions here. In src/files.js import files that you have added then export it. For example
```
import dash from "../dash"
```
then export it like this 
```
export default {
dash
... etc

}
```

**Comment by vadim9999** [comment]
@elnur004 when you exported you files you have delete from export another
why you have deleted this 
```
import measurementSystems from '~/Units/measurementSystems.json'
import measurementUnits from '~/Units/measurementUnits.json'
import generatedMeasurementSystem from '~/MeasurementSystem/measurementSystem.json'
import generatedMeasurementUnits from '~/MeasurementUnits/measurementUnits.json'

import { 
  frenchBeans,
  sprouts,
  jacketPotato,
  sweetPotato,
  kale,
  leek,
  broccoli,
  carrots,
  mushrooms,
  onions_shallots,
  parsnips,
  peppers,
  marrow_squash,
  sweetcorn,
  courgettes 
 } from '../cooking_times'
```
from export?

**Comment by elnur004** [comment]
this was mechanically.  i assume then i repaired this mistake

**Comment by elnur004** [comment]
@vadim9999 is there any task else to do?

**Comment by vadim9999** [comment]
@elnur004  add this variable into src/files.js because if I will publish this package other projects will crash now they will not get access to files measurementSystems, measurementUnits et

**Comment by elnur004** [comment]
`import recipes from '~/Recipe4/recipe.json'` this also add?

**Comment by vadim9999** [comment]
@elnur004 yes
