### ISSUE TITLE
move files, created by Elnur into src/data/

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#211]
Move files from root folder project into src/data/. Create folder like filename but first letter should be uppercase

**Comment by vadim9999** [comment]
@elnur004 make all files that you have added static (to make it in json ).
Now all of files that you have added are objects in js files. You task is to make it static. 
1. delete definision variable and export. Now cup1_2.js is
```
let cup1_2 = {
         americanStandart: "8 tablespoons",
         americanStandartOunces: "4 ounces",
         volume: "120 milliliters",
         weight: "113.4 grams, 1/4 pound"
       };

export default cup1_2;
```
need to delete "let cup1_2 = " then delete semicolon then export of this object.
2. wrap all properties names into quotes. As you see properties names are without it.
In result you have static data

**Comment by vadim9999** [comment]
@elnur004 Change import path in src/files.js

**Comment by vadim9999** [comment]
@elnur004 change in sd/files.js the same thing with cooking_times

**Comment by elnur004** [comment]
@vadim9999 i can't understand properly.
which cooking_times need to change?

**Comment by vadim9999** [comment]
@elnur004 file cooking_times doesn't need to change. Delete constants variables that in files.js in root of project. The main problem that we moved files from root of project into src/data. Now path.resolver can't find your files because we changed file extensions. It's need to change from js into json. Second problem we wrap all objects into one array. this many objects doesn't exists that you can't get access to it. Now you can get access to one array that contains many objects.
in files.js path.resolver return full path to your file that is stored on your disk. It's returns one value. change assigns of path.resolver that returns path of cooking_times

**Comment by vadim9999** [comment]
@elnur004 in root of project in files.js change that variables that they ends with FilePath like other variables

**Comment by vadim9999** [comment]
@elnur004 for example now 
```
pinch
```
should be
```
pinchFilePath
```

**Comment by vadim9999** [comment]
@elnur004  then when will you do this change exported variables. Also change variables in export in src/files.js

**Comment by vadim9999** [comment]
@elnur004 in files.js you haven't exported cooking_timesFilePath, holidayFilePath export it. Also delete from export variables that was imported before

**Comment by vadim9999** [comment]
@elnur004 can you write a list of what files you have moved?

**Comment by elnur004** [comment]
@vadim9999 what to do now?

**Comment by vadim9999** [comment]
@elnur004 I have assigne task for you
