### ISSUE TITLE
move tests from groceristar-fetch

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#235]
Our need to find out what tests we should move here(in sd) from groceristar-fetch.

**Comment by vadim9999** [comment]
@EbrahimKreem @elnur004

**Comment by elnur004** [comment]
@vadim9999 can you explain a little how to do it?

**Comment by vadim9999** [comment]
@elnur004 in groceristar-fetch we have https://github.com/GroceriStar/groceristar-fetch/tree/master/src/projects projects folder. In each project folders are tests. Our goal is to find out what tests we should move

**Comment by elnur004** [comment]
@vadim9999, for example, i want to move `src/projects/ChickenKyiv/test/chickenKyiv.test.js` this test.
how to determine, need this to move or not?
or need such determination?

**Comment by vadim9999** [comment]
I think need tests that will help us

**Comment by vadim9999** [comment]
Make it just copy past without deleting from groceristar-fetch

**Comment by vadim9999** [comment]
fork groceristar-fetch repository then copy file past into sd in src/data/tests make push

**Comment by elnur004** [comment]
@vadim9999 `groceristar-fetch/src/projects/GraphQL/test/files.test.js` name of this file is the same as 
this file `groceristar-fetch/src/projects/ChickenKyiv/test/files.test.js`
need me to change the name of the file in **sd**?

**Comment by vadim9999** [comment]
Then create folder GraphQL and CkickenKyiv in generator and copy this test. Also move from src/data/tests chickenkyiv.test.js into created CkickenKyiv/tests. Safe the same structure like in groceristar-fetch/projects

**Comment by elnur004** [comment]
Now, at first, i have to copy all tests from groceristar-fetch/projects to sd/data/tests.
Then create consistency folders in generator and copy files into those folders, right?

**Comment by vadim9999** [comment]
yes

**Comment by elnur004** [comment]
@vadim9999 there are some **files** in the sd/src/data/tests **the same name** as the groceristar-fetch/src/projects.
what about do them? because they aren't able to paste in the sd/src/data/tests folder.
firstly we need to paste all test files here (in sd), but i can't do it

**Comment by vadim9999** [comment]
First of all let's create structure of folders in generator. It should be 
generator
 |_ projects
    |_GroceriStar
   |_ ChickenKyiv
   |_GraphQL

**Comment by elnur004** [comment]
and then what to do?
just test files should be move there?

**Comment by vadim9999** [comment]
yes,  after will be folder ChickenKyiv create in it folder tests and paste there chickenkyiv.test.js

**Comment by elnur004** [comment]
@vadim9999 here (in sd) in the test folder chickenkyiv.test.js also exist.
what about do that? delete or not?

**Comment by vadim9999** [comment]
Now in folder ChickenKyiv create folder tests and move there chickenkyiv.test.js. and Delete chickenkyiv.test.js from src/data/tests
