### ISSUE TITLE
move method getIngredientsKey() from groceristar-fetch

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#240]
**Is it was created as task at GitHub issues? Please provide an issue number or link**

This task is subtask of https://github.com/GroceriStar/sd/issues/294

**Describe the solution you'd like**

From https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js  move to https://github.com/GroceriStar/sd/blob/master/generator/projects/GraphQL/graphQL function getIngredientsKey()

**Describe alternatives you've considered**

**Additional context**

**Comment by atherdon** [comment]
ok, so you have a question about second link. am i right? @ijb87 what do you think can be the next steps, in order to solve this problem?

**Comment by ijb87** [comment]
I would say create a new file with that name and backup the file and its contents just in case

**Comment by atherdon** [comment]
ok, check that folder and if it will work - show me what you want to do via your code changes

**Comment by atherdon** [comment]
@ijb87 you'll need to fork this repository in order to make changes

**Comment by atherdon** [comment]
@Edebo grap this task, so we can complete #294 in short time
