### ISSUE TITLE
copy function getKeyArrayDepAndIng from groceristar-fetch

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#243]
In groceristar-fetch in src/projects/GroceriStar/groceristar.js we have function getKeyArrayDepAndIng. 
1. Create folder Groceristar and create file groceristar.js in generator. 
2. Copy function getKeyArrayDepAndIng in generator/Groceristar/groceristar.js
3. generate file. 
4. move test from groceristar-fetch for this method. all tests you can find in groceristar-fetch/src/projects/GroceriStar/test/
5. add explanation about this function

**Comment by vadim9999** [comment]
@EbrahimKreem this task for you

**Comment by EbrahimKreem** [comment]
I have a small question, why this module uses JSON data other than a database what is the benefit?

**Comment by vadim9999** [comment]
because it's easy to use. If new interns that anything doesn't know also about databases can open json and see structure of files then write methods. second it's faster then setting connection with db and get from there data. we have some db on loopback. startingup a db on local mechine it's need some machine resources and new interns may doesn't understand how to use it.

**Comment by atherdon** [comment]
@Edebo you can grab this task too

**Comment by Edebo** [comment]
generator folder only exist in Groceristar/sd

**Comment by atherdon** [comment]
not sure how i need to react - can you elaborate?

**Comment by Edebo** [comment]
am to copy getKeyArrayDepAndIng function from groceristar-fetch in src/projects/GroceriStar/groceristar.js
to a generator folder.but the where the generator folder is wasnt specify.the only place i found generator folder is in @groceristar/fetch.Morever the moved function is already in generator folder https://github.com/GroceriStar/sd/blob/master/generator/projects/GroceriStar/groceristar.js

**Comment by atherdon** [comment]
ok, maybe we started to work on it. but this function is empty. i think we need to have a working method here - can you do it?

**Comment by atherdon** [comment]
#374

**Comment by atherdon** [comment]
i think we need to do this and we can close this task:
**5. add explanation about this function**

at `docs` folder we have a second part of readme - please add there information about this method

**Comment by atherdon** [comment]
Ok, it's done
