### ISSUE TITLE
add tests into src/index.test.js

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#253]
add tests that check each file that exist or not. All static data are in src/data/. Make structure like in cickenKyiv.test.js  https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/ChickenKyiv/test/chickenKyiv.test.js
In index.test.js use import from files.js that is in root of project https://github.com/GroceriStar/sd/blob/master/files.js.
Example of importing from files.js you can find here https://github.com/GroceriStar/sd/blob/master/src/data/__tests__/allergy.test.js#L3

**Comment by Edebo** [comment]
@vadim9999,do i have to do same for all file in groceristar-fetch/src/projects/

**Comment by vadim9999** [comment]
@Edebo yes

**Comment by atherdon** [comment]
@Edebo did we finish this task, right?

**Comment by atherdon** [comment]
i think it's done
