### ISSUE TITLE
what we need to do, in order to make Travis CI work without crashes?

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#273]
https://travis-ci.org/GroceriStar/sd

**Comment by atherdon** [comment]
yeah, i think we should take a look at some of our CI jobs, see that we have a lot of errors there and start to close them step-by-step: https://travis-ci.org/GroceriStar/sd/jobs/530993735

**Comment by atherdon** [comment]
actually I see that we very simple mistakes here, and maybe Benitha can solve them

**Comment by hirdbluebird** [comment]
@will be fixed with upcoming merge https://github.com/GroceriStar/sd/pull/304

**Comment by will** [comment]
I don’t need to be fixed >:(

**Comment by atherdon** [comment]
i think this part was done
