### ISSUE TITLE
introduction to our current working scope

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#277]
in order to get some details, please read readme from our other package. SD(static data) is a module, that used at our `groceristar-fetch` module. it has some articles, that I created in order to explain details

https://github.com/GroceriStar/groceristar-fetch/blob/master/README.md

 you can start from it, while Vadim will think about tasks for you
@Edebo

**Comment by atherdon** [comment]
@Pratikshagit you can jump here too

**Comment by atherdon** [comment]
not remember if i shared this file with you @dctalk1234. you can read it too, in order to have some details about what we're doing

**Comment by atherdon** [comment]
@Pratikshagit tell me if you still interested to collaborate with us. I plan to close this task soon

**Comment by Pratikshagit** [comment]
Hi Arthur ,

I emailed you already that i have a full time job now. And will not able to
work on your project. You can close this task. Thanks for considering me.
Good luck with your project.

Best Regards
Pratiksha

**Comment by atherdon** [comment]
@Pratikshagit thank you for letting me know, no problem and good luck with your job.

**Comment by Pratikshagit** [comment]
Thank you for the wishes.!!
