### ISSUE TITLE
change importing in tests on filesObjects 

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#282]
Tests for this task you can find here https://github.com/GroceriStar/sd/tree/master/src/data/__tests__/
In this file tests 
```
cooking_times
cup1
cup1_2
cup1_4
cup1_8
cup3_4
dash
gallon1
pinch
pint1
quart1
tablespoon_1
teaspoon_1
```

For example in https://github.com/GroceriStar/sd/blob/master/src/data/__tests__/cup1.test.js#L3
is import from files.js. Replace this importing by importing from filesObjects.js that is in root of project. 

To import from filesObjects.js you need to use this import 
```
const staticData = require("./filesObjects")
// to get access to allergies use staticData.allergies
```
`staticData` contains data of all files that is stored in src/data. staticData is array that contains all objects. Object contains property name - filename, value - object that was got from file.
staticData.allergies returns object.
`allergies` is a value of property allergies

**Comment by dctalk1234** [comment]
It appears that the first github link is not working.

**Comment by atherdon** [comment]
try again, it's about formatting links here

**Comment by dctalk1234** [comment]
That worked

**Comment by dctalk1234** [comment]
To make sure I'm understanding this right my job is to go through the tests and in for example cup1.test.js file change const {cup1} = require('../../../files.js') to const staticData = require("./filesObjects")

**Comment by atherdon** [comment]
i'm not Vadim, so cannot reply to you exactly. Make your changes, show you code and when we will be ready - he will tell you if you need to change something in your code ;)

**Comment by atherdon** [comment]
Btw, some our other developer, Ebrahim also show interest to make some changes in tests - so be aware about it - because your changes can generate a conflict with his code

**Comment by atherdon** [comment]
did we finish this task?

**Comment by atherdon** [comment]
@Edebo can you grab this task too?

**Comment by atherdon** [comment]
it's done
