### ISSUE TITLE
Move function getUserGroceryKey() from groceristar-fetch

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#302]
**Is it was created as task at GitHub issues? Please provide an issue number or link**

This task is subtask of https://github.com/GroceriStar/sd/issues/294

**Describe the solution you'd like**

From https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js  move to https://github.com/GroceriStar/sd/blob/master/generator/projects/GraphQL/graphQL function getUserGroceryKey(). 

**Describe alternatives you've considered**

**Additional context**

**Comment by Beni03** [comment]
Looks like getUserGroceryKey() has been already moved. Did you ask me to work on task @294?

**Comment by atherdon** [comment]
oops, my bad. closing it then - thanks for letting me know
