### ISSUE TITLE
move getFavoritesKey() from groceristar-fetch

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#303]
**Is your feature request related to a problem? Please describe.**

This task is subtask of https://github.com/GroceriStar/sd/issues/294

**Is it was created as task at GitHub issues? Please provide an issue number or link**

From https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js move to https://github.com/GroceriStar/sd/blob/master/generator/projects/GraphQL/graphQL function 
getFavoritesKey()

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atherdon** [comment]
@wahaj-47 readme message is at low priority - so start issue that gave you Vadim.

**Comment by vadim9999** [comment]
@wahaj-47 Make this steps for method getDepartmentsKey()
