### ISSUE TITLE
move  getItemsKey() from groceristar-fetch

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#309]
**Is it was created as task at GitHub issues? Please provide an issue number or link**

This task is subtask of https://github.com/GroceriStar/sd/issues/294

**Describe the solution you'd like**

From https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js  move to https://github.com/GroceriStar/sd/blob/master/generator/projects/GraphQL/graphQL function getItemsKey()

**Describe alternatives you've considered**

**Additional context**

**Comment by atherdon** [comment]
@Edebo you can grab this task
