### ISSUE TITLE
Move function getUsersKey () from groceristar-fetch

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#327]
**Is it was created as task at GitHub issues? Please provide an issue number or link**
This task is subtask of #294

**Describe the solution you'd like**
From https://github.com/GroceriStar/groceristar-fetch/blob/master/src/projects/GraphQL/graphQL.js move to https://github.com/GroceriStar/sd/blob/master/generator/projects/GraphQL/graphQL function `getUsersKey()`.

**Comment by atherdon** [comment]
@Edebo you can grab this task

**Comment by atherdon** [comment]
perfecto

**Comment by Edebo** [comment]
next task pls
