### ISSUE TITLE
do it 

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#337]
### Expected Behavior / Situation
-  merge your pr
- publish on npm
- install to fetch
- publish fetch at npm
- install updated fetch at fake-api(https://github.com/GroceriStar/fake-api) & graphql-server(https://github.com/GroceriStar/graphql-server)

**Comment by atherdon** [comment]
we need to discuss what we'll do next after that

**Comment by hirdbluebird** [comment]
@atherdon please, leave the list of command to publish, can't find it in repo's

**Comment by atherdon** [comment]
https://github.com/GroceriStar/sd/blob/master/README.md#publish-at-npm

**Comment by atherdon** [comment]
I really need to complete this
