### ISSUE TITLE
review nutriotional attributes/types json file. it wouldn't pass our jsonvalidator

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#338]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1469198/57964837-632ad800-7944-11e9-908e-9516f8e8f512.png)
![image](https://user-images.githubusercontent.com/1469198/57964843-73db4e00-7944-11e9-8223-36d1e4c9165c.png)
![image](https://user-images.githubusercontent.com/1469198/57964846-79d12f00-7944-11e9-825b-1a3ce208b0e3.png)

**Additional context**

**Comment by atherdon** [comment]
@Edebo did we finish it and i can close it as well?

**Comment by Edebo** [comment]
yes we finished it
