### ISSUE TITLE
Carefully move json files tests into root folder

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#384]
### Expected Behavior / Situation
Right now we have mess with our tests. this task will be a first part of our changes.
Current tests located here: ```https://github.com/GroceriStar/sd/tree/master/src/data/__tests__```
rename folder to `tests` and move this folder into the root of the repository

**Comment by atherdon** [comment]
major thing here is carefully. because all tasks inside have imports, and if you just move them to the outside - all tests will be broken. So be careful and avoid it, please

**Comment by brunocordeiro180** [comment]
Done

**Comment by EbrahimKreem** [comment]
I apologize @brunocordeiro180 I didn't know you will make it :sweat_smile:

**Comment by atherdon** [comment]
let's go to another task(don't forget that you'll need to sync your fork) in order to get always a fresh version.
1) move JSONLint file and change path to it at package.json
2) Rename
 - Gallon1 to Gallon
- Pint1 to Pint
- Quart1 to Quart
- Tablespoon_1 to Tablespoon
- Teaspoon_1 to Teaspoon
- 1_2Cup to HalfCup
- 1_4Cup to QuaterCup
- Cooking_times to CookingTimes
you'll also need to update paths at both `files.js` files and update paths at files.js as variable name(2 times)

---

- DietAndHealthLabels -> update/remove the first line, keep only json data.

---

- move tests, that we have at generator/projects/%projectName% to tests/projects/%projectName%

**Comment by atherdon** [comment]
@brunocordeiro180 tell me if something will not clear

**Comment by brunocordeiro180** [comment]
Haha no problem @EbrahimKreem

**Comment by brunocordeiro180** [comment]
@atherdon It is not very clear to me exactly what file to move and where in "move JSONLint file and change path to it at package.json"

**Comment by atherdon** [comment]
> @atherdon It is not very clear to me exactly what file to move and where in "move JSONLint file and change path to it at package.json"

yeah - it was my intentions - i don't want to give you a path to that file so you can search it yourself and get more familiar with project structure ;)

**Comment by atherdon** [comment]
@brunocordeiro180 at this explanation you have at least 2 different ways how to do it

**Comment by brunocordeiro180** [comment]
Done. This time the pull request passed :)

**Comment by atherdon** [comment]
yeah - it's awesome - no bugs then. merged

**Comment by atherdon** [comment]
You can go with next things

**Comment by brunocordeiro180** [comment]
Nice. I'm ready to another task

**Comment by atherdon** [comment]
@brunocordeiro180 did you complete 
- DietAndHealthLabels -> update/remove the first line, keep only json data.
- move tests, that we have at generator/projects/%projectName% to tests/projects/%projectName%

**Comment by brunocordeiro180** [comment]
Yes

**Comment by atherdon** [comment]
then we closing this task :)

**Comment by atherdon** [comment]
I find out another task that is related to this one.
with your latest changes related to measurements parts name, we actually will broke out another module, that related to this module.
please explore this folder: https://github.com/GroceriStar/groceristar-fetch/tree/master/src/projects/UnitConvertion
and update things respectively

**Comment by atherdon** [comment]
i find another part, related to this rename. 
Check this folder and you'll find out what you need to do: https://github.com/GroceriStar/sd/tree/master/tests

**Comment by atherdon** [comment]
@brunocordeiro180 I promise that next tasks will be more interesting to do :)

**Comment by brunocordeiro180** [comment]
@atherdon Thank you hauhauhau

**Comment by atherdon** [comment]
all is done here
