### ISSUE TITLE
json-schema modification [addon]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#423]
1) Move json schemes into the separated variable outside of `describe` block. it will make tests looks less complicated
2) move out example into the separated file, move out scheme into the separated file - maybe it should be one file with 2 exported variables...
3) configure rollup bundler, so with build -> we copy only json files from data folder at build, and skip tests/schemas/examples...
#22

**Comment by atherdon** [comment]
@siddharthp538 you can grab it
tell me if you need more information

**Comment by siddharthp538** [comment]
cool. will do it

**Comment by siddharthp538** [comment]
> 1. Move json schemes into the separated variable outside of `describe` block. it will make tests looks less complicated
> 2. move out example into the separated file, move out scheme into the separated file - maybe it should be one file with 2 exported variables...
> 3. configure rollup bundler, so with build -> we copy only json files from data folder at build, and skip tests/schemas/examples...
>    #22

@atherdon  what exactly do u mean by the 3rd point?

**Comment by siddharthp538** [comment]
i'm done with the first 2, i'm not understanding what exactly needs to be done for the 3rd one? @atherdon

**Comment by atherdon** [comment]
can you open a pull request with that changes?

**Comment by atherdon** [comment]
and i think you did it pretty quick - especially that we need those changes for each test file - that was updated...
And before going into point 2 i was hoping to see all files working after changes of point 1

**Comment by siddharthp538** [comment]
oh, i am sorry. I made a PR. Have a look. @atherdon

**Comment by atherdon** [comment]
no problem - all is fine - this is why i'm assigning these tasks for you - so you can have more practice

**Comment by atherdon** [comment]
@AndrewSerra this task touch a lot of files, so you can jump into it and help Siddharth

**Comment by atherdon** [comment]
can you open a pull request with that changes?

>

**Comment by siddharthp538** [comment]
@atherdon a little busy right now. Will do it once I'm free. Sorry for the delay

**Comment by atherdon** [comment]
let's start with first one and i'll elaborate lately the last one

>

**Comment by siddharthp538** [comment]
just explain what needs to be done. I'll try to do it ASAP

**Comment by siddharthp538** [comment]
Can you tell me what was wrong with my last PR? Didn't they solve the first two points?

**Comment by AndrewSerra** [comment]
So is there only the third step left?

**Comment by atherdon** [comment]
@AndrewSerra nope. please start with step one only and apply it for a few test files

**Comment by atherdon** [comment]
@siddharthp538 problem with your latest PR is simple - few days ago, when you fork our repo you apply some changes. Then Adebowale update one file that I merged to master. you change the same file with Adebowale, but you didn't sync your fork with his changes. it creating merge conflict. and i asked you to rebase your pull request(branch) in order to get changes from Adebowale and I was able to approve your changes. in future - each time when you want to make code changes - you need to sync your fork and pull changes to your repository

**Comment by atherdon** [comment]
@siddharthp538 it maybe solves the first two points - but it was done for one test file(and we have a lot of files and each one require these changes) and it creates `merge conflict`,

**Comment by siddharthp538** [comment]
Okay. Noted

**Comment by siddharthp538** [comment]
@atherdon  for the shema of the first file, allergy.test.js
"Seafood-Free",
"Gluten-Free" 
all these should have value of 1 or 0 right?

**Comment by atherdon** [comment]
@siddharthp538 for some reasons your message didn't appears here.
I'll put it here
> for the shema of the first file, allergy.test.js
"Seafood-Free",
"Gluten-Free"
all these should have value of 1 or 0 right?

@Edebo can you advise, because i'm not quite sure

**Comment by siddharthp538** [comment]
@atherdon I'm done with the option 1, but only with those files who were already tested. Should I make a PR? or You'll review it tomorrow directly after i'm done for all files?

**Comment by atherdon** [comment]
yes, please open a PR so I can take a look

>

**Comment by siddharthp538** [comment]
@atherdon  i'm not able to make a PR. "Create Pull Request" button is disabled. Any help?

**Comment by atherdon** [comment]
> @atherdon i'm not able to make a PR. "Create Pull Request" button is disabled. Any help?

Hmm, maybe you didn't commit/push your changes to your fork?

**Comment by siddharthp538** [comment]
I did

**Comment by siddharthp538** [comment]
@atherdon i made a PR. Have a look

**Comment by atherdon** [comment]
jump into next thing while i'm figure out what is going on :)
falling asleep

**Comment by AndrewSerra** [comment]
I've worked on eleven files on the version I have forked.  Should I continue with all of them or should go to the second step? because I'm not sure which ones @siddharthp538 has completed.

**Comment by AndrewSerra** [comment]
@atherdon also sorry I was a bit slow, I was going through the airbnb style guide

**Comment by atherdon** [comment]
@AndrewSerra  no problem - it's not an issue, because it's hard to jump into new project, with changes that we made also quickly. you'll get that pace - just will take some time

**Comment by atherdon** [comment]
@ijb87 you can join this task as well

**Comment by AndrewSerra** [comment]
Should I continue with all the files or would you like to have a look at the ones I have done?

**Comment by atherdon** [comment]
show me what you done. i like small steps approach, especially when we have a lot of people, working on this particular task @AndrewSerra

**Comment by ijb87** [comment]
@AndrewSerra @siddharthp538 do any of you guys have a discord or something we can communicate through in order to make sure we're on the same page?

**Comment by atherdon** [comment]
it's better to use GitHub for communication. because only here all team is
connected. please use these comments for it.

>

**Comment by atherdon** [comment]
one of the easiest ways is to look at the last changes, that were made. check pull requests - that I merge and mentioned at this thread, then you'll be able to see what was done. then compare file that was updated with another file and you'll find out are the same(i.e both completed) or not. just made some groundwork and research code more and everything will be clear

**Comment by AndrewSerra** [comment]
@atherdon to show you what I have completed should I create a pull request? Currently, I forked the repository and made changes there. How do we do the checking?

**Comment by atherdon** [comment]
watch this
https://github.com/ChickenKyiv/awesome-git-article#forking-pull-requests

**Comment by AndrewSerra** [comment]
Thanks. I'm working on it now, there are some conflicts that I have to resolve

**Comment by atherdon** [comment]
you will need to sync your fork

>

**Comment by AndrewSerra** [comment]
Once I did the sync I most of the files are done in a different way already or the files were deleted but I have gone through all the files and realized that not all of them have the same style, should I change them so they are consistent in style?

**Comment by AndrewSerra** [comment]
I now have the repository properly set up so I hopefully won't have the same problem again my bad.

**Comment by atherdon** [comment]
i don't usually understand when i don't see code.
if you think there should be some update in "style" - do it and open a pull
request. then i'll see it and tell if it ok or not

and i think good lesson here - don't wait a lot and submit changes quickly

>

**Comment by AndrewSerra** [comment]
Okay since my files were done I'll so some small quick changes so all files match and open a pull request

**Comment by atherdon** [comment]
@AndrewSerra your files not gone. this is why git and github is a good thing. you can see your history of commits or roll soeme changes back - i don't want to lose your previous work. let's think how we can bring it back - if it's not duplicate of someone e;se work

**Comment by AndrewSerra** [comment]
@atherdon It is very similar that's why I did not mind. Right now the schemes and examples change for the same variable name. I had all examples and schemes as their own constant since the second step of the issue says the can be exported from different files. Maybe I misunderstood task two.

**Comment by siddharthp538** [comment]
@atherdon  i'm done with testing of almost of all files. That ends option 1 as well. I have made a PR. I'm starting with option 2. cool?

**Comment by siddharthp538** [comment]
@AndrewSerra  @ijb87 can we start with the second task? It's simple enough but a repetitive thing, we can distribute it and get our stuff done quickly, I feel.

**Comment by AndrewSerra** [comment]
@siddharthp538 sure I'll start it but I didn't fully understand what is meant

**Comment by siddharthp538** [comment]
> @siddharthp538 sure I'll start it but I didn't fully understand what is meant

This is the task : move out example into the separated file, move out scheme into the separated file - maybe it should be one file with 2 exported variables...

Still any doubt?

**Comment by siddharthp538** [comment]
> > @siddharthp538 sure I'll start it but I didn't fully understand what is meant
> 
> This is the task : move out example into the separated file, move out scheme into the separated file - maybe it should be one file with 2 exported variables...
> 
> Still any doubt? let me know

**Comment by atherdon** [comment]
yes please start with second part of task, but please everybody be aware
and sync your fork with our repository - because i'll merge a lot of new
changes in 1 hour or so

>

**Comment by AndrewSerra** [comment]
@siddharthp538 Still not totally sure. What I understood is having a file that is similar to files.js for both examples and schemas, is that right?

**Comment by siddharthp538** [comment]
> @siddharthp538 Still not totally sure. What I understood is having a file that is similar to files.js for both examples and schemas, is that right?

have a look at tests/dashexamples.js something like that.

**Comment by siddharthp538** [comment]
@AndrewSerra  created tests/example/ 
we'll add all the files there.
tell me which files you'll are willing to take. I have already did option 2 for few files.

**Comment by atherdon** [comment]
example is very unclear name. I.e "example of what?" or "if there examples,
why we have schemas as well?"

>

**Comment by siddharthp538** [comment]
> example is very unclear name. I.e "example of what?" or "if there examples, why we have schemas as well?"
> […](#)

i meant examples of all the schema's

**Comment by AndrewSerra** [comment]
@siddharthp538 got it. I'm assuming you went alphabetically, I can complete from gallon.test.js to quart.test.js?

**Comment by siddharthp538** [comment]
works for me @AndrewSerra

**Comment by AndrewSerra** [comment]
I have made a pull request for the files starting from gallon.test.js to quart.test.js @siddharthp538 just to let you know

**Comment by AndrewSerra** [comment]
> I have made a pull request for the files starting from gallon.test.js to quart.test.js @siddharthp538 just to let you know

*when you list them alphabetically

**Comment by siddharthp538** [comment]
> > I have made a pull request for the files starting from gallon.test.js to quart.test.js @siddharthp538 just to let you know
> 
> *when you list them alphabetically

cool, i'll do the remaining files and then we'll start with option 3.

**Comment by atherdon** [comment]
i think we also need tests that will prevent errors of not finding
examples/schema files

>

**Comment by siddharthp538** [comment]
> i think we also need tests that will prevent errors of not finding examples/schema files
> […](#)

could not get you?

**Comment by atherdon** [comment]
?

>

**Comment by siddharthp538** [comment]
> i think we also need tests that will prevent errors of not finding examples/schema files
> […](#)

can u elaborate a little?

**Comment by atherdon** [comment]
Sure, imagine this situation - i'll delete whole folder that contains
examples/schemas. without tests it will just crash. but tests will show use
that something is wrong here

this is actually a similar test case that we have with out json files

>

**Comment by atherdon** [comment]
@elnur004 you can jump into this task with very simple improvement.
you can go through files that we have and update this line
```
const schema = require('./examples/users').schema
const example = require('./examples/users').example
```
with 
```
const { schema, example } = require('./examples/users')
```

**Comment by AndrewSerra** [comment]
> Sure, imagine this situation - i'll delete whole folder that contains examples/schemas. without tests it will just crash. but tests will show use that something is wrong here this is actually a similar test case that we have with out json files
> […](#)

@atherdon so you mean adding extra test cases that check all files are there? or a simple try/catch block?

**Comment by atherdon** [comment]
i like both! Do both!
:)
extra cases and try/catch is a good thing to implement here

**Comment by AndrewSerra** [comment]
Nice! I can work on that or should I continue with step three? If I'll be working on error handling, for the try/catch should it just be a 
`try {
 require('./example/a_file.js')
}
catch (e) {
 console.log(e)
}` 
block that writes to console or something else? For the test cases can they be a file that has a describe block containing all it and expect for all the necessary files?

**Comment by atherdon** [comment]
we don' ready for step 3 yet.
about try/catch - show me code changes at pull requests - its better for my
understanding

**Comment by AndrewSerra** [comment]
@atherdon should I do one and make a pull request so you could see? after that, I can continue with the rest and add them all to the same pull request

**Comment by atherdon** [comment]
@AndrewSerra looks like your changes break our builds. error log
```
 /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:3:1: 'expect' is not defined.
  /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:5:1: 'describe' is not defined.
  /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:6:3: 'it' is not defined.
  /home/travis/build/GroceriStar/sd/tests/testFilesCheck/exampleFiles.test.js:7:5: 'expect' is not defined.
```

**Comment by siddharthp538** [comment]
@atherdon I won't be available this week. Sorry, have to complete my college project.

**Comment by atherdon** [comment]
@siddharthp538 no problem at all - take your time - no rush here

**Comment by atherdon** [comment]
Andrew, I fixed that issue

>

**Comment by AndrewSerra** [comment]
@atherdon what was causing it to be not defined? I checked all other files and couldn't figure it out

**Comment by AndrewSerra** [comment]
Do we have anything left for step 2?

**Comment by atherdon** [comment]
i don't know - you tell me.
Do you think we cover all json files? Are you really really sure? because
i'm always unsure

>

**Comment by AndrewSerra** [comment]
I think we are done. The last part I have done checks all the files under the examples/ directory, so all the schemas and examples that are used in the tests/ directory.

**Comment by atherdon** [comment]
will you bet on that that we're done? :)

>

**Comment by AndrewSerra** [comment]
> will you bet on that that we're done? :)
> […](#)

nope :)

**Comment by atherdon** [comment]
me too - then spend some time and try to answer to the question - what
files were covered and what is not. i mean we can also create some methods
as well - that can help us or some of our team members to answer to that
question in future as well

>

**Comment by siddharthp538** [comment]
can u assign a new task? @atherdon

**Comment by atherdon** [comment]
yes i can but for me this task is not finished yet

>

**Comment by atherdon** [comment]
try to find static files, that we have in this repo - and they were not covered yet with json schema test

**Comment by AndrewSerra** [comment]
@atherdon do you mean any files that we have missed to create as <filename>.test.js

**Comment by AndrewSerra** [comment]
Also under tests/projects/ directory, I don't know if there were typos creating the file names, but some of the tests under the project folders have names such as "loopback.teszt.js" Just wanted to ask because it may be a typo even though they are all commented out except for graphQL at the moment.

**Comment by atherdon** [comment]
this is my "work" - we didn't finish test coverage for that files and i
just rename them, in order to remove them from testing process.
You can create a separated task/github issue - specify each file and some
new teammate will be able to deal with it

>

**Comment by siddharthp538** [comment]
@AndrewSerra  can u pls explain me what is done and what is left?

**Comment by atherdon** [comment]
@vadim9999 grab it here as well. it mostly done, but not finished

**Comment by AndrewSerra** [comment]
@siddharthp538 sorry for the late response, I'm having quite a rough week. So what I have completed is a try/catch block for the test.js files so the test does not crash if for some reason a file is missing and we could not import the schema and example. The second thing I have done is the tests/testFilesCheck/ directory. The two files under that directory get all the file names under tests/examples/ and export an object. Then the exampleFiles.test.js files contain manually written tests to check if the key in the object is undefined or not. 

For what needs to be done: as far as I understand we have to find static files where we have missed to create tests.

**Comment by AndrewSerra** [comment]
@atherdon I found a couple more, do we need tests for Derivation_Code_Description, DietAndHealthLabel, Product, and ServingSize? These are under src/data/ and they all have csv files except for DietAndHealthLabel.

**Comment by atherdon** [comment]
yes we need it. i think when it will be done - we'll be able to finish this
big topic with tasks and focus on the next things

>

**Comment by AndrewSerra** [comment]
I'll start with **Derivation_Code_Description** then. Also, I will add them under food composition in files.js since the json file is under generator/ they can all be together and easier to see when the paths change later

**Comment by AndrewSerra** [comment]
If anyone has not done DietAndHealthLabel doing it now then openning a pull request

**Comment by AndrewSerra** [comment]
@atherdon I don't know if I understood it right but in some test files, there are imports similar to this 
```
const { typesFile } = require('@files')
const types = require(typesFile)
```
and I found similar ones in a couple of files which return undefined for the one coming from ./src/files.js because it is not present in the file. The second line returns an empty object. Is this supposed to be like this?

Also, another thing is that I am completing the final two tests which are Product and ServingSize. Since it is similar to Nutrition, I went through that [issue](https://github.com/GroceriStar/sd/issues/531#issuecomment-505762254) and saw that the `readAllFiles(path)` function which returns all the objects stored in all the json files in the directory. Do we need all the content?

**Comment by atherdon** [comment]
@vadim9999 can you advice @AndrewSerra here?

from my side - open PR and we'll take a look on it :)

**Comment by AndrewSerra** [comment]
I have written the example file and the test works at the moment, the problem is the json path, that we check as the first test in every file. for example this piece of code:
```
describe('foodComposition data files returns a path', () => {
  it('these tests prevent any issues and problems, also to break the structure of foodComposition', () => {
    expect(foodComposition).not.toBe('')
  })
})
```

I could still use path resolver where I only check the path of one json file, since all of them are in the same directory. In that case I can add it to src/files.js

**Comment by AndrewSerra** [comment]
I can open a pull request before I open a pull request, should I do what I have just mentioned in the previous comment?

**Comment by AndrewSerra** [comment]
@atherdon nevermind I have made tests for both that check all paths I'll open a pull request so you and @vadim9999 can see what I have done and if it is right.

**Comment by vadim9999** [comment]
@AndrewSerra yes, create working variant and open PR

**Comment by AndrewSerra** [comment]
@vadim9999 Already done.

**Comment by AndrewSerra** [comment]
@atherdon It looks like we completed the tests, at least the ones I have noticed, should we start step 3?

**Comment by atherdon** [comment]
@AndrewSerra i think we should jump at another task with you.
As you think this was done - i'll close this task.
I separated a step 3 at #595, so we don't forget about it.

Thinking about your next tasks now

**Comment by atherdon** [comment]
@siddharthp538 do you need another task as well?

**Comment by siddharthp538** [comment]
yes @atherdon
