### ISSUE TITLE
We need to split our big object with grocery lists into separated files, each file = one grocery list object

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#424]
i keep it without good task explanation for a reason. want to provoke a discussion here.
Please ask your questions. @uniyalprashant9

**Comment by atherdon** [comment]
@amogh-jrules as it's a big task - let's go from it. but it pretty simple

**Comment by amogh-jrules** [comment]
@atherdon Do we have to write scripts which take in a large object and break it down and generate smaller files?

**Comment by atherdon** [comment]
if you want - yes. we actually have our generator script - that you can use for this kind of task.
my goal here - to split our old version of file/database into small files in order to easily manipulate them
and by working on this task, same to @uniyalprashant9 - you'll learn about the current structure of grocery lists(which maybe soon will be changed)

**Comment by atherdon** [comment]
for generator explanation - check Readme file

**Comment by atherdon** [comment]
@amogh-jrules @uniyalprashant9 please connect together in order to deal with this task. because we need to solve it together - not twice, so it's about collaboration task, not about competition

**Comment by amogh-jrules** [comment]
Will do

**Comment by uniyalprashant9** [comment]
We have to write a script for splitting these files `https://github.com/GroceriStar/sd/tree/master/src/data/Grocery`  ( grocery.json and grocery0.json ) into multiple JSON files each with one element ??

**Comment by amogh-jrules** [comment]
Yes that's the goal I guess

**Comment by atherdon** [comment]
what is the difference between `grocery.json` and `grocery0`? just don't remember

**Comment by amogh-jrules** [comment]
I ran it through https://www.diffchecker.com, only one line is different rest all is the same

**Comment by atherdon** [comment]
got it

**Comment by uniyalprashant9** [comment]
This should be the desired output or need some changes?? 
Each file has one element from grocery.JSON and the file name is the same as the name attribute of each element.
![Screenshot from 2019-05-31 22-34-31](https://user-images.githubusercontent.com/36094606/58722164-5d2d0080-83f4-11e9-9cbd-c9e52bc2a405.png)

**Comment by atherdon** [comment]
1) can you replace JSON with json
2) did you made it inside of our module?
3) can you open a pull request and so I can publish it on our repository?

>

**Comment by atherdon** [comment]
other thing looks well(but we'll need to check it with our tests and
JSONLint script)

>

**Comment by uniyalprashant9** [comment]
Ok, I will change JSON to json .
I made that separately to test if it works or not, I will put in our module and open a pull request.

**Comment by atherdon** [comment]
cool main reason - we need it to work as part of our module, because later
we'll be able to change the structure of our data and import it into
databases with different structure

>

**Comment by uniyalprashant9** [comment]
@atherdon I made few changes in the script, now it creates a seperate directory for each object of the same name and put respective elements inside the directory.  

If you need all the elements in one folder I will change it again.

I opened a pull request for the same.

**Comment by atherdon** [comment]
1) We need to create an `index.js` file and import all of created json files there.
you can see as example `src/files.js` so our files will be accessible from the outside
2) we should write tests for all files(connecting them to tests from `index.js` that we will create)
3) we should add information to our readme - so other team members will know about our changes.
4) how do we can call this script? do we have a package.json script for it?
5) I think that part of your code can be replaced with an actuall code that we have at generator folder right now.

please go from first point, doing them step-by-step and pushing pull requests separately.

**Comment by uniyalprashant9** [comment]
@atherdon I didn't understand what is to be done in point 1.

I have to make `index.js ` file which will import all the json files that were splitted from the large object file grocery.json and it will return a list of all the elements??

**Comment by atherdon** [comment]
i think yes, something similar to https://github.com/GroceriStar/sd/blob/master/src/index.js

**Comment by uniyalprashant9** [comment]
Which ourput is required for 1

A)list of files 
or 
B)an object that has all the content of the splitted files.
A=> 
![Screenshot from 2019-06-01 22-04-33](https://user-images.githubusercontent.com/36094606/58751261-130e5280-84ba-11e9-833a-933c2924f6a8.png)


B=> 
![Screenshot from 2019-06-01 22-04-59](https://user-images.githubusercontent.com/36094606/58751266-1acdf700-84ba-11e9-9eff-7bc46880b977.png)

**Comment by atherdon** [comment]
actutally both will be useful :)
Make 2 methods but for now we'll use the first one

**Comment by uniyalprashant9** [comment]
OK i will make the first one as `index.js` and the second one as `indexContent.js`

**Comment by uniyalprashant9** [comment]
For 2, I have made a test.
Please check is it ok, then I will open a new pull request.
Writing test is new for me so it took time. 😅

That error in the screenshot was made intentionally to check if it is working or not. Then I reverted it back and made a final one.

![Screenshot from 2019-06-02 12-26-33](https://user-images.githubusercontent.com/36094606/58757921-03325500-8532-11e9-81ee-7c605b6f3863.png)

**Comment by uniyalprashant9** [comment]
@atherdon I have one doubt, I have used mocha for the test , will it get errors when running it in Travis CI?

**Comment by uniyalprashant9** [comment]
@atherdon  Please check my pull request, I have one more test module to upload. 😅

**Comment by uniyalprashant9** [comment]
I am currently working on readme file.

**Comment by uniyalprashant9** [comment]
@atherdon  I need some help for making tests.
tests are working in my laptop but not working when I opened a pull request so I canceled that pull request. 😅

**Comment by atherdon** [comment]
let's do this way - show me that changes by opening a pull request. because it hard to discuss them while i don't see code. and there, at pull request comments please explain in details what exact help you need - and i'll help you

**Comment by uniyalprashant9** [comment]
> 1. We need to create an `index.js` file and import all of created json files there.
>    you can see as example `src/files.js` so our files will be accessible from the outside
> 2. we should write tests for all files(connecting them to tests from `index.js` that we will create)
> 3. we should add information to our readme - so other team members will know about our changes.
> 4. how do we can call this script? do we have a package.json script for it?
> 5. I think that part of your code can be replaced with an actuall code that we have at generator folder right now.
> 
> please go from first point, doing them step-by-step and pushing pull requests separately.

I am merging splitObject.js in the existing generateArray.js file in generators and then will do a readme.MD update.

**Comment by atherdon** [comment]
Ok, but please be careful with changes. Or create tests or ask for advice about tests as well.

**Comment by atherdon** [comment]
Btw, it's still not clear for me - are we merge your changes or not? @uniyalprashant9 - you made some moves and my head is going around

**Comment by uniyalprashant9** [comment]
> Ok, but please be careful with changes. Or create tests or ask for advice about tests as well.

Yes I will

**Comment by uniyalprashant9** [comment]
> 1. We need to create an `index.js` file and import all of created json files there.
>    you can see as example `src/files.js` so our files will be accessible from the outside
> 2. we should write tests for all files(connecting them to tests from `index.js` that we will create)
> 3. we should add information to our readme - so other team members will know about our changes.
> 4. how do we can call this script? do we have a package.json script for it?
> 5. I think that part of your code can be replaced with an actuall code that we have at generator folder right now.
> 
> please go from first point, doing them step-by-step and pushing pull requests separately.

splitObject() is in writeFile.js to split json files
getList() and getListContent() are in utils.js to retrive json files.
readme is updated.
how to call those functions is explained in readme.md.
the old splitObject.js is already merged in existing file (writeFile.js)

**Comment by uniyalprashant9** [comment]
Only test part is remaining.

**Comment by uniyalprashant9** [comment]
@atherdon

**Comment by atherdon** [comment]
can you handle a testing part on your own or do you need help with it? we have a pretty cool test folder where you may find some similar tests that you can copy and connect to this task

**Comment by uniyalprashant9** [comment]
> can you handle a testing part on your own or do you need help with it? we have a pretty cool test folder where you may find some similar tests that you can copy and connect to this task

@atherdon  Most of the tests are to match the schema of json files, my modules split large json files into single files, retrive list of files in the directory,  they don't need tests I guess splitObject will work on parameters passed.

**Comment by atherdon** [comment]
yes, that tests for schema. but not only for schemas only. take deeper look

>

**Comment by atherdon** [comment]
and no guessing - we have tests for that ;)

**Comment by atherdon** [comment]
@uniyalprashant9 what is left for this task?

**Comment by uniyalprashant9** [comment]
@atherdon  only tests are remaining

**Comment by atherdon** [comment]
can you do them?

>

**Comment by uniyalprashant9** [comment]
yes i will :)

**Comment by atherdon** [comment]
@vadim9999 garb it here too. looks like we almost finished it but i'm have doubts that all of my comments was actually done/implemented

**Comment by vadim9999** [comment]
ok

**Comment by vadim9999** [comment]
I think it's done
