### ISSUE TITLE
items/favorites/usergrocery should be moved away from Ingredients folder

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#47]
@wahaj-47  you can do this too - very quick task

**Comment by atherdon** [comment]
let's complete this quick task, so i'll be able to remove it from my memory

**Comment by wahaj-47** [comment]
Where do I move it to ?

**Comment by atherdon** [comment]
for now - just create a separated folders

**Comment by atherdon** [comment]
dont forget about another 2 files

**Comment by atherdon** [comment]
awesome. closing
