### ISSUE TITLE
.vscode folder in root repo folder

### ISSUE THREAD

**Issue by hirdbluebird** [GroceriStar/sd#470]
**Describe the bug**
Wrong PR request merge

**To Reproduce**
Go to repo

**Expected behavior**
No folder of visual studio code

**Additional context**
Check carefully PR's

**Comment by atherdon** [comment]
add it to .gitignore

**Comment by atherdon** [comment]
can you add it to gitignore i dont want to do it

**Comment by atherdon** [comment]
as you don't know how to use gmail during development process
