### ISSUE TITLE
Tasks list for Adebowale

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#481]
Just want to have a separate place in order to improve our process
- [ ] #471 
- [x] #332

**Comment by atherdon** [comment]
another idea was to try our sd at our fake-api project. it should work without any troubles, but we don't know it yet. and we can start to preparing our fake-api to be able to handle our React Showcase project

**Comment by Edebo** [comment]
#332 seen the repository created and i agree with you.

**Comment by Edebo** [comment]
> another idea was to try our sd at our fake-api project. it should work without any troubles, but we don't know it yet. and we can start to preparing our fake-api to be able to handle our React Showcase project
i think we should do this,to be first sure our sd is working perfectly without any trouble.

**Comment by Edebo** [comment]
#471 awesome-food-db-strucutures/USDA-01-06-2019/Serving_Size.xlsx has over 237910 objects when converted to json .what is the maximum number of objects that  will be appropriate in each file when the main one is split

**Comment by atherdon** [comment]
> what is the maximum number of objects

i dont' know but for now, i think for us it will be enough to have just some(100 or 1000) entities. because having a lot of data is cool, but not necessary in our current stage

**Comment by atherdon** [comment]
> i think we should do this,to be first sure our sd is working perfectly without any trouble.

https://github.com/GroceriStar/fake-api/issues/130

**Comment by Edebo** [comment]
so sorry,you havent heard from me,for a while,having issues with electricity in this part of the world

**Comment by atherdon** [comment]
no a problem at all - take as much time as you need

**Comment by Edebo** [comment]
i already did the spliting of awesome-food-db-strucutures/USDA-01-06-2019/Serving_Size.xlsx  into several json file using sd logic,but i used a max entry of 10000 so as to get 24 json files,which i think shouldnt be overwhelming.if i use max entry of 1000,we will be getting 238 json files

**Comment by atherdon** [comment]
push your changes via PR first.
and  then i'll reply :)

**Comment by atherdon** [comment]
i'm ok with both options. like few long files or more files.
But i think we should use this situation as source of improvement. we should extend logic of our split function, so we can pass there a number of entries in order to be able to manipulate it outside.

again, plese be careful with changes - because it may affect work of other files that generated - just to let your know

**Comment by Edebo** [comment]
How can i keep up now.
I will like to do a task

**Comment by atherdon** [comment]
I think we should start with syncing your fork with current version of repository. because we made some organizing changes and moved away part of code that you was working on before.
So please sync your fork and then buzz me about your next task

**Comment by Edebo** [comment]
done

**Comment by atherdon** [comment]
Let's do a quick task now.
As this repository growing - it's pretty hard to understand what is doing on with code and how it's connected through the folders..
at our 2 other repositories, which contains part of code that you was working here we made some reogranizations.
take a look at the main difference and can try to do the same thing here?
generator: https://github.com/GroceriStar/food-static-files-generator
csv-parser: https://github.com/GroceriStar/food-datasets-csv-parser

**Comment by atherdon** [comment]
ok, let's think about next moves.
1) delete `repo-pore` folder
2) delete `runner`
3) remove https://github.com/GroceriStar/sd/tree/master/package/data/USFA because we have that dataset inside of csv-parser at this moment...
4) clean up https://github.com/GroceriStar/sd/blob/master/package/src/files.js#L78-L89

**Comment by Edebo** [comment]
You said clean up and not delete.but the only food composition is in https://github.com/GroceriStar/sd/tree/master/package/data/FoodComposition and it has no json file in it except readme

**Comment by atherdon** [comment]
yep - this is why we'll remove it from that file. by clean up i mean that maybe something else should be done as well in this file but i don't know what :)
easiest way is try run module and see what is broken now

**Comment by atherdon** [comment]
remove this line as well: https://github.com/GroceriStar/sd/blob/master/package/package.json#L17

**Comment by Edebo** [comment]
ok

**Comment by Edebo** [comment]
the readme too should be updated

**Comment by atherdon** [comment]
https://travis-ci.org/GroceriStar/sd/jobs/610025581 we have some eslint errors here.
you can run it on your side for easy debug

**Comment by atherdon** [comment]
next part will be to understand if something working wrong at build.
so please try to run build locally - rollup build and if it's fine - we'll make a new npm release and will think about our next steps

**Comment by Edebo** [comment]
finding it hard to npm i ,telling me 
![synk](https://user-images.githubusercontent.com/36434800/68580668-206f3600-0477-11ea-9e54-98f38e9c190b.png)

**Comment by atherdon** [comment]
can you remove `npm run snyk-protect` from package,json script?
and try to run it again - maybe it will help

>

**Comment by Edebo** [comment]
done

**Comment by atherdon** [comment]
next thing will be - move fileObjects method into utils and change other files imports accordingly.

and let's chat about 2 similar files: filesES5.js and files.js.
do you think we still need to have both of them?

**Comment by Edebo** [comment]
we should remove filesES5.js because is a duplicate of files.js. also we should compress data in package folder with data in src folder and make appropirate changes

**Comment by atherdon** [comment]
but why we have it before?

>

**Comment by Edebo** [comment]
i dont know.might be different people working on it at the same time

**Comment by atherdon** [comment]
got it. thanks - i'm not remember as well. maybe we use it for some kind of
reasons.
i mean as we have a lot of stuff inside of sd before - it was used. but
now, as we make it more clear - it's awesome - because it was rudimentary.

what do you think can be improved next? should i make a release of our
changes at npm, right?

>

**Comment by Edebo** [comment]
reduce code climate troubles.

**Comment by atherdon** [comment]
ok, let's try to clean up our codeclimate dashboard a bit - in meantime i'll take a look at code and find what we can do next

**Comment by Edebo** [comment]
in our tests ,we use import from files while in other we import from filesObject though deleted but function in utils

**Comment by atherdon** [comment]
ok, can it will be replaced with new version?

>

**Comment by Edebo** [comment]
yes it can

**Comment by Edebo** [comment]
how do we know our tests is run properly.because i made a change to test.i want to test if it is working for single file before i replicate for other files

**Comment by atherdon** [comment]
i think you can perform test by running `cd package`, `yarn test`

>

**Comment by atherdon** [comment]
as we jumping away - i think we dont need this task anymore
