### ISSUE TITLE
measurements methods

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#512]
**Is your feature request related to a problem? Please describe.**
I think that we should try to do task from fetch here. I'm talking about https://github.com/GroceriStar/groceristar-fetch/issues/399
And I think we can firstly do it here - because it's a main reason why we have files - and then we'll move it to the fetch plugin

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Beni03** [comment]
Hi Arthur,
I was trying to understand this task, but I am not very clear of what I should do. 
1. In SD repo, we already have filesObjects.js and I think it has all those files in to one object right?  
2. What are measurement files? all json files inside data folder? 
Can you please give me some more details to understand this task
Thanks

**Comment by atherdon** [comment]
1) yes
2) we have 2 files related to measurement system. it's called measurement
system and measurement units. right now they're separated. when you'll do
this task, later we'll work on merging them into one structure

>

**Comment by Beni03** [comment]
Got it! thanks

**Comment by atherdon** [comment]
Can you create few simple methods, that will use functionality that you did in prev PR and return measurements files to the outside?

also, next move can be to combine few files that have objects into one big object

we have this code, but i don't remember how it actually works
https://github.com/GroceriStar/sd/blob/master/generator/generateArray.js#L106-L140
can you take a look and figure it out?

**Comment by Beni03** [comment]
Yes I’ll try to do this

**Comment by atherdon** [comment]
ok, closing it.
Do you have another task or i should create a new one for you?

**Comment by Beni03** [comment]
I don’t have any other task right now. Can you please create a new task?
