### ISSUE TITLE
Copy generator methods into new place

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#523]
As we plan to move our generator out - we preparing a separated space for it.
Our readme file has good explanation of generator methods and you should copy it into this repository: https://github.com/GroceriStar/food-static-files-generator

**Comment by atherdon** [comment]
@amogh-jrules you can grab this quick task while Prashant not replied

**Comment by amogh-jrules** [comment]
I'm working on it
thanks

**Comment by atherdon** [comment]
cool - i'm here for any help

>

**Comment by amogh-jrules** [comment]
So do I copy the generator methods from this repo to the new one ie /food-static-files-generator following the readme for the generator file? just confirming once

**Comment by atherdon** [comment]
yep

>

**Comment by amogh-jrules** [comment]
i have one question, the generateFiles.js does not have an export statement written, if we are to move it an external wrapper as we are doing it, should'nt it require one?

**Comment by amogh-jrules** [comment]
The rest of the readme i have added and suitably modified

**Comment by atherdon** [comment]
cool suggestion, yes, please do an export from generateFiles.js

>

**Comment by atherdon** [comment]
but only at sd repo right now. we quite not ready to move all functionlaity
out right now. but we're working on it
