### ISSUE TITLE
json validation

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#53]
@wahaj-47 you'll need to complete task that i didn't finish.
details at this file: https://github.com/GroceriStar/sd/blob/master/jsonlint.config.js

we'll need to run the same validation for all of our json files

**Comment by atherdon** [comment]
#60

**Comment by atherdon** [comment]
let's jump here, because it's easier for me.

So, what exactly is not clear for you?

Let's split everything in small chunks.

1) we're returning an object from files.js. objects at JS are similar to arrays. Can you grab the whole object and make a loop?
2) right now we have 2 files with same purpose but with different syntax. Do you think we'll be able to use ES6 version instead of ES5 in jsonconfig?

**Comment by atherdon** [comment]
3. You told me that right now jsonconfig script is not working, right? do you know why? and how we can solve it?

**Comment by wahaj-47** [comment]
1. Yes I can do that. 
2. We don’t have files with same purpose. But yeah I suppose we can use the es6 one. 
3. All the paths are undefined. We need the right paths to json.

**Comment by atherdon** [comment]
1. Ok, please do it
2. i think you tell me that we have 2 similar files...
3. i think it's because of an issue in `require` and it can be easily fixed(i.e. change to the right path)

**Comment by atherdon** [comment]
I also think that es6 version will work, but i didn't test it. And first version of `jsonlint` file was created before  my upgrade of logic how this whole package will be translated by Babel

**Comment by atherdon** [comment]
maybe, we need to rename files.js to something less confusing.
for example old part from `jsonlint` can be renamed to files-es5.js and another file can be renamed to `files-es6.js`

**Comment by wahaj-47** [comment]
> 1. Ok, please do it
> 2. i think you tell me that we have 2 similar files--> [#60 (comment)](https://github.com/GroceriStar/sd/pull/60#issuecomment-478266760)
> 3. i think it's because of an issue in `require` and it can be easily fixed(i.e. change to the right path)

2. They are not similar.

**Comment by wahaj-47** [comment]
```
import {
    allergies
} from './src/files'
```

If I use this in jsonlint.config.js I get 

import {
            ^

SyntaxError: Unexpected token {

**Comment by wahaj-47** [comment]
Why not use babel for jsonlint as well ?

**Comment by atherdon** [comment]
I don't know - you think you can do it without me? if you can do it without
me and it will work fine - i'm 100% agree to do it
our babel script pointed to `src` folder. So `jsonlint` file should be
moved in that case

>

**Comment by wahaj-47** [comment]
Using require still gives me syntax error.
Moving the jsonlint file to src folder doesn't make any difference

**Comment by atherdon** [comment]
let's do it in small steps.
1) create a file `jsonlint2.js` inside `src` folder
2) instead of require - use import and connect one static file - allergies.json
3) import shelljs aswell to that file
4) run `exec()` function for that one file
5) add an additional line to package.json in order to call our new file from a command line
6) save everything and run our new script

**Comment by atherdon** [comment]
i find some strange thing....
right now at our package.json - we don't have a raw shelljs module.
I replaced it with shx, which is a wrapper on shelljs. and it has shelljs inside, but not as our main package...
if jsonlint works  - it's really strange...

**Comment by wahaj-47** [comment]
> let's do it in small steps.
> 
> 1. create a file `jsonlint2.js` inside `src` folder
> 2. instead of require - use import and connect one static file - allergies.json
> 3. import shelljs aswell to that file
> 4. run `exec()` function for that one file
> 5. add an additional line to package.json in order to call our new file from a command line
> 6. save everything and run our new script

Done...No luck
I think babel is not working

**Comment by atherdon** [comment]
pull request with your changes and i'll take a look

**Comment by atherdon** [comment]
while i'm working on it - please switch to another tasks that you have

**Comment by atherdon** [comment]
i see some issue, at our `jsonlint.config.js` file.
I comment whole logic and print only files. please take a ook, by running `yarn jsonlint`

**Comment by atherdon** [comment]
tell me if you'll need help here, i have some free time right now

**Comment by wahaj-47** [comment]
What issue are you talking about ?

**Comment by wahaj-47** [comment]
jsonlint2.js still not working, means babel's still not working

**Comment by atherdon** [comment]
did you read my previous comment?

**Comment by atherdon** [comment]
I mean this https://github.com/GroceriStar/sd/issues/53#issuecomment-479814991

**Comment by wahaj-47** [comment]
Yeah we're doing module.export in the files.js and importing them in jsonlint file. We're getting the right paths but, We've already exported the jsons in src/files.js, why do it twice ?

**Comment by atherdon** [comment]
because it looks differently right now. If you think you can deal with it and make one file instead of two - i'm ok with that. But right now our goal to finish task with jsonlint.
What is your plan or if you have some changes - please open pull request so I can take a look

**Comment by wahaj-47** [comment]
Are you sure babel is working fine ?

**Comment by atherdon** [comment]
300% sure in babel and trust in our code for 20% only

**Comment by atherdon** [comment]
do you need confirmation or you ok with my words :)

**Comment by wahaj-47** [comment]
Ok :D

**Comment by atherdon** [comment]
guys that code babel have $10k salaries, so their code is cool

**Comment by atherdon** [comment]
So what will be our next steps, in order to crack this task?

**Comment by wahaj-47** [comment]
> guys that code babel have $10k salaries, so their code is cool

I didn't mean that babel is broken, I meant that we've setup babel wrong.

**Comment by atherdon** [comment]
i think this is not the case. i mean i understand why you think it can be, but it's probably some of your or my mistakes in code, not in setup. If you think you cannot deal with it - i can find another task for you

**Comment by atherdon** [comment]
ok, forget about last question - didn't receive a notification about your PR. when you run `yarn jsonlint` - did you saw some errors? because i think i saw them previously(before our changes).
Plus, you can remove jsonlint file from src folder - as we don't need it

**Comment by wahaj-47** [comment]
Nope I didn’t see any errors when running yarn jsonlint. Just some console.logs of paths

**Comment by atherdon** [comment]
ok, then it's work well. please push changes that i requested in prev message(don't forget about package.json) and i'll think about next task for you

**Comment by atherdon** [comment]
ok, this is done
