### ISSUE TITLE
add test coverage for Nutrition

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#531]
https://github.com/GroceriStar/sd/tree/master/generator/projects/USFA/Nutrition

**Comment by atherdon** [comment]
@AndrewSerra

**Comment by amogh-jrules** [comment]
Can I take this up?

**Comment by atherdon** [comment]
yes you can

>

**Comment by atherdon** [comment]
@vadim9999 will check it

**Comment by amogh-jrules** [comment]
@atherdon hey, I am a bit confused, what exactly am I supposed to be doing..?

**Comment by atherdon** [comment]
find a folder nutritions at generator/USFA
we don't have tests for that huuuge set of files.
tell me if it doesn't have a separated `files.js` i think i created one,
but not sure if i push it to master branch.

we need to do a similar test coverage.
not empty, plus check for shema.

but we cannot do it by copypaste - it's a suicide. at some places in
generator i think we have a method that list all files in one folder...
find it

**Comment by amogh-jrules** [comment]
there is no files.js inside the nutrition folder, I found this however 
>at some places in generator i think we have a method that list all files in one folder...
>find it

https://github.com/GroceriStar/sd/blob/master/generator/projects/USFA/files.js it is entirely commented out i think this is the one you are talking abour

**Comment by vadim9999** [comment]
I think you need method readAllFiles(path) that located in utils. you can find it in /src/utils

**Comment by amogh-jrules** [comment]
@atherdon  there is no files.js, can you please push it

**Comment by atherdon** [comment]
just added it, but Vadim right - we should do an import of files recursevely. my way is bad. i just did it for quick way

link: https://github.com/GroceriStar/sd/blob/master/generator/projects/USFA/Nutrition/files.js

**Comment by amogh-jrules** [comment]
I have a few doubts,
what should the tests check for apart from schema?
what platform should I write the tests for ie, Travis or jest?

**Comment by atherdon** [comment]
right now we're doing only 2 kid of tests for our json files:
- if file exists and return data
- if data match to the scheme

> what platform should I write the tests for ie, Travis or jest?

Hmm, it's not correct question i think.
- framework for testing is Jest
- Travis is a CI/CD tool that work as we configure it. we add to run `npm
test` script so it's checking if something doesn't crash after our changes

**Comment by amogh-jrules** [comment]
Oh ok understood, thanks
I start working on it

**Comment by atherdon** [comment]
@amogh-jrules tell me if you need help with this task

**Comment by amogh-jrules** [comment]
> I think you need method readAllFiles(path) that located in utils. you can find it in /src/utils
Just one thing I don't understand what is the output of this method will be, as in what format,is there a way for me to run that particular file?

**Comment by atherdon** [comment]
@AndrewSerra can you advise here?

**Comment by AndrewSerra** [comment]
@amogh-jrules 

`readAllFiles(path)` is a function that read all files under the directory you have specified for `path`.  For the json files it takes all objects and adds them to an array. The array is returned. 

I used something different if you want to check the file `./tests/product.test.js` The first test check whether you have a path and whether it is undefined. The second test inside the try/catch block check if the schema matches the example.

While working you can run the files under tests/ directory. When I wasn't sure about a function I used `console.log()` to see what it returns, whether I get the paths I want, and so on... Then you can use the command ```npm test <the-file-you-are-working-on>.test.js``` and it will show the result of the test and what you have logged with `console.log()`

**Comment by amogh-jrules** [comment]
> While working you can run the files under tests/ directory. When I wasn't sure about a function I used `console.log()` to see what it returns, whether I get the paths I want, and so on... Then you can use the command `npm test <the-file-you-are-working-on>.test.js` and it will show the result of the test and what you have logged with `console.log()`

Thanks so much, exactly what I needed, I'll get right to it

**Comment by AndrewSerra** [comment]
> > While working you can run the files under tests/ directory. When I wasn't sure about a function I used `console.log()` to see what it returns, whether I get the paths I want, and so on... Then you can use the command `npm test <the-file-you-are-working-on>.test.js` and it will show the result of the test and what you have logged with `console.log()`
> 
> Thanks so much, exactly what I needed, I'll get right to it

Glad to help!

**Comment by amogh-jrules** [comment]
Hey I have another issue, I tried working it out but couldnt. when I run npm test, it gives a error saying CI is not a recognised function, what is that I should install so that works?

**Comment by amogh-jrules** [comment]
The npm test function invokes CI && jest, so I npm installed jest and ran it seperately, but still it fails to run

**Comment by atherdon** [comment]
jest is part of our setup. you don't need to install it separately.
Please tell more details or shoot video about how you trying to run this
module.
Because we test it few days ago and it was working fine

>

**Comment by amogh-jrules** [comment]
![Untitled](https://user-images.githubusercontent.com/31567169/60538867-7dfeb380-9d1c-11e9-9b46-d791e81330d6.png)

**Comment by atherdon** [comment]
you can run whole test coverage `npm run test`

>

**Comment by amogh-jrules** [comment]
That is not working either... it used to before
Should I re-clone the repo and try again?

**Comment by atherdon** [comment]
you can sync your fork with the main master branch.
https://github.com/ChickenKyiv/awesome-git-article#keeping-a-fork-up-to-date

**Comment by atherdon** [comment]
after sync you should reinstall node_modules

**Comment by amogh-jrules** [comment]
Ok ill do that

**Comment by amogh-jrules** [comment]
filesES5.js has the import statements for different JSON files but the syntax is written in ES6 format and that is causing errors when I run it, is there another file which contains those names?

**Comment by atherdon** [comment]
@AndrewSerra can you advise here?

**Comment by AndrewSerra** [comment]
can you send the error? @amogh-jrules

**Comment by amogh-jrules** [comment]
Its basically a syntax error repeated throughout the file 
in ES5 import statements are eg. const files = require(path)
but in ES6 we can  use import files from path, the filesES5.js has ES6 syntax which is given an invalid syntax error

**Comment by amogh-jrules** [comment]
It's alright, I can handle this, I'll change the syntax to suit our requirements

**Comment by amogh-jrules** [comment]
Can I use nutritionalAttributes.js for all the schemas and examples? Because nutrition.test.js defines a few new schemas seperately
PS. Files im talking about are in ..tests/examples/

**Comment by atherdon** [comment]
i think yes, if it will work for this case

>
