### ISSUE TITLE
Fix "TODO" issue in generator/writeFile.js

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#559]
TODO found

https://codeclimate.com/github/GroceriStar/sd/generator/writeFile.js#issue_5d0989133836940001000237

**Comment by atherdon** [comment]
@jan-strum  please check if this was not done, because i'm not sure

**Comment by jan-strum** [comment]
@atherdon It looks like someone resolved this issue, but I don't feel I have enough context to be sure.

**Comment by atherdon** [comment]
hold on, i'll take a look

**Comment by atherdon** [comment]
you did a great work :) closing it. jump to another task that I mentioned you

**Comment by jan-strum** [comment]
Ha. I'm looking at it now. I'll email you if I have any questions.
