### ISSUE TITLE
at this folder we have tests. they should work

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#56]
Folder: https://github.com/GroceriStar/sd/tree/master/src/data/__tests__
as you can see - each file has similar content. I create test only for allergy file and then copy paste it. Your task will be: connect proper json files and add them into tests.
Each json file should be covered

**Comment by atherdon** [comment]
@ronniebhatt you can grab it

**Comment by ronniebhatt** [comment]
Error 404 on the above link

**Comment by atherdon** [comment]
https://github.com/GroceriStar/sd/tree/master/src/data/__tests__
