### ISSUE TITLE
Fix "TODO" issue in generator/generateFiles.js

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#560]
TODO found

https://codeclimate.com/github/GroceriStar/sd/generator/generateFiles.js#issue_5d098913383694000100023d

**Comment by atherdon** [comment]
@/jan-strum you can grab this one, if you need details - buzz me

**Comment by atherdon** [comment]
it will increase our code quiality and remove a similar code that we have before

**Comment by jan-strum** [comment]
@atherdon On line 13, do you want functions for the path manipulations which are then called inside of `generateFiles`?

**Comment by jan-strum** [comment]
@atherdon Referring to line 35, what script would `generateFiles()` be called in? Or should I just remove it for now?

**Comment by atherdon** [comment]
@vadim9999  please advice here - i'm falling asleep

**Comment by vadim9999** [comment]
> @atherdon On line 13, do you want functions for the path manipulations which are then called inside of `generateFiles()`?

Yes, create separated method and call it from generateFiles()

**Comment by jan-strum** [comment]
Okay. I just started a coding challenge that will take several days, so I
won't be able to get to this for a while.

**Comment by vadim9999** [comment]
> @atherdon Referring to line 35, what script would `generateFiles()` be called in? Or should I just remove it for now?

Yes remove line 35 and move code outside of the function generateFiles. It will be automatically running without calling any function that to start generator

**Comment by jan-strum** [comment]
Hi. Sorry for being so absent; I've been very busy these past two weeks. I
have some time to work on this now, so I'll take a look in a couple of
hours.

**Comment by atherdon** [comment]
we made some changes in our code structure - and some tasks maybe not need
to be solved

>

**Comment by jan-strum** [comment]
Ok. Could you remove the TODOs for those tasks if they are no longer
relevant, please? I'm ready for whatever other assignments you have for me.

**Comment by atherdon** [comment]
i'm buzy with other things :)  will remove them later.

you can jump into this task https://github.com/GroceriStar/food-datasets-csv-parser/issues/27
