### ISSUE TITLE
Callback for splitObject

### ISSUE THREAD

**Issue by uniyalprashant9** [GroceriStar/sd#567]
Let's also add a backward method, that will combine splited files into a big one. But do it in a more elegant way. as the last attribute - we'll pass a callback, that will operate the structure of `object` inside of that array.
  
  For example.
  I want to combine all grocery lists together. but for one case I want to have
  
  ```
  - grocery
    - id
    - name
    - ingredients
    - departments
    - purchased
  ```
  
  for the second case
  
  ```
  - grocery
    - id
    - name
    - items
      - all
      - purchased
  ```
  
  and I want to do manipulations with structures at callbacks. 
  Plus, in the end, it should call a write file for sure...

**Comment by uniyalprashant9** [comment]
@atherdon

**Comment by uniyalprashant9** [comment]
@atherdon  Let this be sample content in grocery
~~~
    [{
        "departments": [
            "shopping list",
            "each week buy",
            "detox vegetable broth ingredients"
        ],
        "id": 27,
        "name": "dr-ozs-rapid-weight-loss-plan-shopping-list",
        "img": false,
        "desc": false,
        "slug": false
    },
    {
        "departments": [
            "Other"
        ],
        "id": 14,
        "name": "number-four9",
        "img": false,
        "desc": false,
        "slug": false
    }]
~~~

so should this module return ??

~~~
[{
        "id": 27,
        "name": "dr-ozs-rapid-weight-loss-plan-shopping-list",
        "departments": [
            "shopping list",
            "each week buy",
            "detox vegetable broth ingredients"
        ]
    },
    {
        "id": 14,
        "name": "number-four9",
        "departments": [
            "Other"
        ]
    }]
~~~

**Comment by atherdon** [comment]
@vadim9999 please grab this one

@uniyalprashant9 yep, this can be one of the cases. structure, like 
```
{
        "id": 14,
        "name": "number-four9",
        "departments": [
            "Other"
        ]
```
should be manipulated inside of that callback.

btw, my assessment was to create a combineObjects method with callback, but as you started this one - let's do it twice. hope it's ok for you. just more practice.

how i see it.
example.
```
functionAAA = (object) => {
for object

  - new__object = {xxx}
return new_object
}

splitObject(args, functionAAA)
```

**Comment by vadim9999** [comment]
Do you want me to create this method or just check PR?

**Comment by atherdon** [comment]
Vadim,. only check PR when it'll be published

>

**Comment by uniyalprashant9** [comment]
@atherdon How if the function `combineObject()` will get the list of keys (or index of keys assuming that the user knew what are the serial of keys in structure) to be not to be included while combining??

This will be handier for the user to manipulate the structure as required as he can decide which keys are not required.

**Comment by atherdon** [comment]
show the code - this is what i can tell you :) looks like a cool idea, but
open PR and Vadim will advice you about it

>
