### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#592]
**Is your feature request related to a problem? Please describe.**

@svr8 This module contains static data and generator. The generator creates new static data from functions. Now I am moving the generator into a separated module. Additional information you can read here Readme https://github.com/GroceriStar/sd/blob/master/README.md and https://github.com/GroceriStar/sd/blob/master/generator/Readme.md.

**Is it was created as task at GitHub issues? Please provide an issue number or link**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atherdon** [comment]
please add more details to this task

>

**Comment by svr8** [comment]
Hi! I have skimmed through the files in `generator` folder and looked deep into the `writeFile.js` script. Please tell me about how to proceed further.

I tried installing npm_modules. It gives me an error. I'm not sure about the current state of the project right now, is that a work still under progress/already addressed? Otherwise, I'll open an issue with the details.

**Comment by vadim9999** [comment]
Synchronize your branch with the current, if a bug still exists please create a bug report in issues

**Comment by atherdon** [comment]
Thiank you for that task!

tell us if you have question about how it works, or maybe let's just jump at some simple task that we have at our generator code. i think it'll be the easiest way to get head around of what we're doing here/

Actually, Vadim - Shikhar has a great knowledge at backend, so when he'll learn about our coding process and help us with generator - i think you can form a great team at some of our backend tasks.

**Comment by atherdon** [comment]
for example @svr8 if you ready to jump at code, you can take a look at this issue : https://github.com/GroceriStar/food-static-files-generator/issues/46
or 
https://github.com/GroceriStar/food-static-files-generator/issues/69
