### ISSUE TITLE
Testing generator 

### ISSUE THREAD

**Issue by vadim9999** [GroceriStar/sd#597]
**Is your feature request related to a problem? Please describe.**

To run generator use this command:
```
npm run generate
```
after this in data folder should be regenerated three files. You don't need anything to configure just run command. Configuration file is located in separated repo 
**Is it was created as task at GitHub issues? Please provide an issue number or link**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vadim9999** [comment]
@atherdon Please test generator from your PC. I just want to know if path is working. Command 
```
npm run generate
```

**Comment by atherdon** [comment]
ok, i'm on it

>

**Comment by atherdon** [comment]
@AndrewSerra can you test it on your local machine as well?

**Comment by AndrewSerra** [comment]
> @AndrewSerra can you test it on your local machine as well?

of course

**Comment by AndrewSerra** [comment]
I'm getting this
```
Andrews-MacBook-Pro-4:sd andrew$ npm run generate

> @groceristar/sd-wrapper@4.11.3 generate /Users/andrew/Desktop/GroceriStar/sd
> node ./generator/generate

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '@groceristar/static-data-generator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/andrew/Desktop/GroceriStar/sd/generator/generate.js:1:89)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @groceristar/sd-wrapper@4.11.3 generate: `node ./generator/generate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @groceristar/sd-wrapper@4.11.3 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by atherdon** [comment]
@vadim9999 Not clear for me - I should clone code from this repo, install modules and run this command, right?

**Comment by AndrewSerra** [comment]
Oh wait, is this,  `@groceristar/static-data-generator`, another repository that I need to have?

**Comment by atherdon** [comment]
i got it Vadim - this issue at sd repo :)

> static-data-generator
I think @AndrewSerra it's module from this github repo: https://github.com/GroceriStar/food-static-files-generator

**Comment by AndrewSerra** [comment]
Mine works too, fixed it I had a missing dependency :)

**Comment by atherdon** [comment]
@vadim9999 i'm running this SD module at GitPod build machine, because locally i have another bracnch(projects2.0) locally

@AndrewSerra what did you install?

**Comment by AndrewSerra** [comment]
@atherdon I downloaded this from npm `@groceristar/static-data-generator`

**Comment by AndrewSerra** [comment]
where should the third generated file be?

**Comment by atherdon** [comment]
so we forget to install it and push to our main repo, right?

**Comment by AndrewSerra** [comment]
I guess yes

**Comment by AndrewSerra** [comment]
Also, I found the third file but I guess it is the same as the pushed version so it did not show up. All good

**Comment by atherdon** [comment]
looks like main repo has that module. all is fine for me at GitPod

![image](https://user-images.githubusercontent.com/1469198/60448317-0b170f00-9c2e-11e9-97e2-4b5bca3b0dbd.png)


i think it's fine - jumping into my code work

**Comment by vadim9999** [comment]
Thanks for testing. There is a bug in generating the third file. I have assigned it to @AndrewSerra

**Comment by atherdon** [comment]
I think we should close this task
