### ISSUE TITLE
finish eslint and lint-staged configuration

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#654]
**Is your feature request related to a problem? Please describe.**
pretty similar to what was done at generator module

and you can also remove standard package when eslint will be 100% configurated

**Comment by vadim9999** [comment]
Working on it

**Comment by atherdon** [comment]
it's done

**Comment by atherdon** [comment]
i'll remove a standard, so we don't need it after eslint setup.
I saw warning at husky - maybe you can move husky configuration outside the package.json at husky.config.js file?
