### ISSUE TITLE
eslint errors

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#737]
**Describe the bug**
I made some updates at master branch, so please sync your fork.
I run eslint and find some simple errors. can you fix them?

Btw, did you know that i created ~4 courses on Udemy? I can share them with you for free - just not remember if i did it before.

**Comment by Edebo** [comment]
sorry this is late.i ran npm run lint and cannot find the error.
You havent shared them with me before. would like have them.Thanks so much

**Comment by atherdon** [comment]
don't worry - you never late. hold on, will try to run lint on my side today - maybe they gone. or maybe you need to sync your fork and re-install the latest package updates? btw, will figure it out soon.
will share those courses today with you

**Comment by atherdon** [comment]
you correct - can't find anyerrors at this point. what should we do next then? do you want to stay a bit at this repository and maybe improve it a bit or we can jump into something new

**Comment by Edebo** [comment]
i think we should republish at this stage first,if we have no error,we can jump to something new.

**Comment by atherdon** [comment]
can you clarify what do you mean by republish? 

we plan to make some moves with this package soon. but i don't have inspiration for that in this moment :)

**Comment by atherdon** [comment]
falling asleep, will share courses when wake up. just a long day

**Comment by atherdon** [comment]
My free courses. will share with others as well. by Udemy rules - they free only 3 days - so add them to cart so they can go to your collection.

- https://www.udemy.com/course/learn-css-flexbox-practically/?referralCode=6B1FF79042D1E4023794
- https://www.udemy.com/course/git-basics-and-merging-process/?couponCode=781761DA14E7F63DB436
- https://www.udemy.com/course/git-workflows-in-depth/?couponCode=683F95090F26178D9BDB
- https://www.udemy.com/course/anatomy-pull-requests-in-depth/?couponCode=A6633E23A9B563BFEE1E
- https://www.udemy.com/course/start-to-use-github-pull-requests-like-a-master/?couponCode=2F2616EDB22C66FE2958
- https://www.udemy.com/course/advanced-scenarios-git-commands/?couponCode=EAC483FE2B508646861A

**Comment by Edebo** [comment]
What i mean is to publish it

**Comment by Edebo** [comment]
Thanks for the courses

**Comment by atherdon** [comment]
OK, then we'll jump to something else while i'm preparing plan for next
steps of this repository.
and you welcome - i'm happy to help with courses. and when you finish them
- they will generate a certificate that you can add to your linkedin
profile.
i mean everyone want to see them, right? so it's additional perk of doing it

>

**Comment by atherdon** [comment]
closing it
