### ISSUE TITLE
diets, health labels, etc

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#95]
https://github.com/ChickenKyiv/awesome-food-db-strucutures/blob/master/README.md#nutritional-attributes
https://github.com/ChickenKyiv/awesome-food-db-strucutures/blob/master/README.md#types

**Comment by atherdon** [comment]
your goal to convert that data into clean JS objects @ronniebhatt

**Comment by ronniebhatt** [comment]
Do you want in .js file or .JSON file

**Comment by atherdon** [comment]
json file please

**Comment by ronniebhatt** [comment]
ok

**Comment by atherdon** [comment]
when you'll add files here, create a test for that file as well. example of test you can find a this project

**Comment by atherdon** [comment]
and then you should connect files, that you created into main index.js so we can use it outside of this module

**Comment by atherdon** [comment]
@ronniebhatt are you still with us or should i reassign this task to someone else?

**Comment by ronniebhatt** [comment]
I am busy with my College examination , you can give this task to other

**Comment by atherdon** [comment]
ok, will do.
Good luck with exams btw!
will you back to us after them?

>

**Comment by atherdon** [comment]
@Edebo you can grab this task as well

**Comment by ronniebhatt** [comment]
Sir I won’t be able to continue my tasks

**Comment by atherdon** [comment]
@ronniebhatt not a problem I understand.
@Edebo i think we finish this task, am i right?

**Comment by Edebo** [comment]
yes

**Comment by atherdon** [comment]
awesome. closing it
