### ISSUE TITLE
adding tests. part 1

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/sd#96]
All of our static files need to be tested. Imagine this situation: someone by mistake break the structure of our file. Then we publish these changes to our main project and everything went down. In order to prevent similar situations - we'll add test coverage to our files. So we'll feel safe, about our changes.
Right now I split tests, between files. I actually duplicate a test for allergies. So we'll need to change that.
https://github.com/GroceriStar/sd/tree/master/src/data/__tests__
https://github.com/GroceriStar/sd/blob/master/src/data/__tests__/allergy.test.js

here you can see how we connect to our files: https://github.com/GroceriStar/sd/blob/master/src/files.js

another thing to update: 
- [ ] you need to replace 'xxx' with a proper explanation of what our tests 
doing(checking is file health labels exists) 

when it will be finished - please open a pull request and submit your 
changes to the main repository, please

@elnur004

**Comment by elnur004** [comment]
hi! 
i looked over the tests and i didn't understand what i need to do to solve this task. 
can you give me a bit more hint please?

**Comment by atherdon** [comment]
yes, no problem
1) open test, related to allergies
2) open test, related to diets
3) compare these files, re-read task description and explain to me what we should update

**Comment by atherdon** [comment]
check this video: https://www.loom.com/share/9af63291859a43788cc53bc281b7e267

**Comment by atherdon** [comment]
will give you one hint - some of our files are gone, and some files was added recently...

![xxx](https://media.giphy.com/media/rdma0nDFZMR32/giphy.gif)

**Comment by elnur004** [comment]
what i did wrong?

**Comment by atherdon** [comment]
all is fine. just be ready that this task is not so easy as it can looks like

**Comment by atherdon** [comment]
keep going, you doing everything ok

**Comment by elnur004** [comment]
may be i can't figure out the meaning of "test" of this task

**Comment by elnur004** [comment]
i tried to do as you said in video but every time anything was failed

**Comment by atherdon** [comment]
you still doing all things fine. lets split this task into two parts:
1) right now you are doing changes in previously created tests
2) adding tests for the newest created files

so right now continue to change labels(but it's not necessary to have very different names right now)
pick one and use it as a template between files.

at this moment you're working on first part - let's finish it and then we'll talk about next one

**Comment by atherdon** [comment]
all tests are working together/ So for example we have 10 tests and if one
is broken(our situation) all will be failing - it's how tests works. this
is why we doing this :)

>

**Comment by elnur004** [comment]
we don't have `attribute2.0.test.js` file and there is a conflict in the `nutrition.test.js` file (in the import file there is `nutritions1` not `nutrition`) also `recipe.ck.test.js` doesn't exist.

**Comment by atherdon** [comment]
Yeah, you right.
1) attribute2.0 - adjust to **tezt** so it wouldn't run right now. later
we'll address that
2) nutrition - maybe we need to have a few test files for each file that we
have?
3) please add recipe.ck.test.js

>

**Comment by elnur004** [comment]
hey, @atherdon is this the right way to change the test like this?

**Comment by elnur004** [comment]
i mean attribute2.0

**Comment by atherdon** [comment]
https://github.com/GroceriStar/sd/pull/121#issuecomment-482355427

**Comment by elnur004** [comment]
what do i need to do now?

**Comment by atherdon** [comment]
let's answer to this question - do we have test files for each json file
that we have respectively?

>

**Comment by elnur004** [comment]
we didn't have one or two files like attribute2.0. 
am i understand the question true?

**Comment by atherdon** [comment]
yeah - you right - few other test files is missing

>

**Comment by elnur004** [comment]
and what do we need to do now?

**Comment by atherdon** [comment]
we need to add few *.test.js files for missing json files(i think Units )
should be covered

>

**Comment by elnur004** [comment]
ok. how we can do these?
if it wouldn't be trouble to you may you explain it to me, please?

**Comment by atherdon** [comment]
no prob
at folder __tests you should create a few files. each one should be related
to json file that didn't have a test file before
inside of this files you should import file and add `describe` block

>

**Comment by elnur004** [comment]
from where i will know which file i have to create?
for example, i create units file. is it true?
if this is not true, may you show how to do this, please?

**Comment by elnur004** [comment]
i know i bother you, but i want to learn accurately

**Comment by elnur004** [comment]
hey, @atherdon 
i have created `favorites` and `items` files.  but there aren't their folders in data. need we create those folders?

**Comment by elnur004** [comment]
hi,
what to do now?

**Comment by atherdon** [comment]
for favorites, items and userGrocery - we'll generate json files on the fly. it's partially done right now.
later move files will be generated on the fly as well.
i plan to add more tests, but that task is not ready and i'm spending few days without PC, so can reply slowly

you can jump into new task: https://github.com/GroceriStar/sd/issues/135
I'm closing this task - i think it's done
